### PR TITLE
Bug 1121863 - Undo action in SMS

### PR DESCRIPTION
**Pull request by kumarrishav**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=38df5ddc20f848d3fcdc3b51fb00b1d2cb977c6d

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6eb504f05cc673e8de032daea9c955b580d33441

**Comment by kumarrishav** [comment]
Logs:
[No undo action]

Object { body: "Hello!", id: 11, lastMessageSubject: undefined, lastMessageType: "sms", participants: Array[1], timestamp: 1427983877940, unreadCount: 0, messages: Array[0] } thread_list_ui.js:511:0
Object { body: undefined, id: 10, lastMessageSubject: undefined, lastMessageType: "mms", participants: Array[2], timestamp: 1427983337940, unreadCount: 0, messages: Array[0] } thread_list_ui.js:511:0
"no undo"       thread_list_ui.js:542:8

[Undo action]

Object { body: "Hello!", id: 11, lastMessageSubject: undefined, lastMessageType: "sms", participants: Array[1], timestamp: 1427983988948, unreadCount: 0, messages: Array[0] } thread_list_ui.js:511:0
Object { body: undefined, id: 10, lastMessageSubject: undefined, lastMessageType: "mms", participants: Array[2], timestamp: 1427983448948, unreadCount: 0, messages: Array[0] } thread_list_ui.js:511:0
undefined thread_list_ui.js:530:0
TypeError: thread is undefined thread_list_ui.js:982:20

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6bda5d82fcc71cc4e105c7e6e83d56dce171f397

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=163d1cddad59a483246696b9aa28a331d753d395

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e2459f1ae9e8de10f9bb59b49c037a11624cc946

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c2958388e3ce95105ea766e0b0f7d34b086c0d26

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=058df7836e8ac3e185cf3b9f7e5ba6a0fd196738

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2872f6d40cc4d96f497c43ae67a714717b399071

**Pull request closed without merging**
