### PR TITLE
Bug 1146687 - [Dialer] Localize withheld number string to bdi element

### PR DESCRIPTION
**Pull request by steveck-chung**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3176dd53748cb6f2b3e24486908f4834f87e3b02

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3176dd53748cb6f2b3e24486908f4834f87e3b02

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4467ed55b94e8c9e7885b9b6d51eaf11061d6e74

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#8GHcB7tHQg6RT_PWp6xlgQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5c40478beb21e59b981964fac039000e1313a63e

**Pull request merged**
