### PR TITLE
Bug 1129580 - [RTL][Gallery][Video] The Date Taken information is not displayed in proper RTL format (Year/Month/Day) when viewing the meta-data for pictures and videos.

### PR DESCRIPTION
**Pull request by mermi**
Change format Date 
screendate

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d3b656b8c7a036dc39521c639c5d203656981315

**Comment by anaran** [comment]
Is there a bugzilla bug tracking this issue?
A quick search I tried didn't find a match.

**Comment by mermi** [comment]
Yea there is the Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1129580

Manel Rhaiem(Mermi),
Mozilla Representative in Tunisia

**Comment by anaran** [comment]
Thanks for the quick reply, @mermi , I would have never found that bug.

You probably got a note referencing
https://github.com/mozilla-b2g/gaia/blob/master/CONTRIBUTING.md
in your pull request.

Perhaps that page should point out the commit messages requirement directly, which is currently hidden way at
https://developer.mozilla.org/en-US/Firefox_OS/Developing_Gaia/Submitting_a_Gaia_patch#Easy_patch_submission_with_Autolander

It's also contradicted by
https://developer.mozilla.org/en-US/Firefox_OS/Developing_Gaia/Submitting_a_Gaia_patch#Manual_patch_submission
which does not call for including the bug number.

I guess all of this explains why autolander complains so often about not finding a bug number in a commit.

**Comment by anefzaoui** [comment]
/me hopping in.
Hey Manel, please use this format for your Pull Request (and future ones also):
Bug XXX - Bug Full Name
as @anaran said it should be 
`Bug 1129580 - [RTL][Gallery][Video] The Date Taken information is not displayed in proper RTL format (Year/Month/Day) when viewing the meta-data for pictures and videos.` so the Github gaia bot can attach your PR to the right issue on Bugzilla.
Thanks!

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e1b1753b433f831c8459b7a2aee998c98d2a2635

**Comment by mermi** [comment]
At First I thought it should be resolved from the gaia, but I was wrong it just need to change from the  locomotion, Sorry, I'll close this PR

**Pull request closed without merging**
