### PR TITLE
Bug 1069353 - Listen for screenreader click events in lockscreen slider ...

### PR DESCRIPTION
**Pull request by eeejay**
...module.

### CODE REVIEW

**Comment by try-server-hook** [comment]
[eeejay Eitan Isaacson (eeejay)](https://github.com/eeejay) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e6406550bbda)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=976d137e6b3ba65f34e5a2d9526e553ab1b6683f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bb8eabde7067759bb3e845f44e8e74601f71bf2c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8dc0b01a56385da913224296a6d0563b7e25cf29

**Pull request merged**
