### PR TITLE
Bug 1126953 - Autolander test bug, remove strings for quick settings dialog +autoland

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1126953

### CODE REVIEW

**Comment by try-server-hook** [comment]
[KevinGrandon Kevin Grandon (KevinGrandon)](https://github.com/KevinGrandon) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2a88e3f08fe1)

**Comment by try-server-hook** [comment]
[KevinGrandon Kevin Grandon (KevinGrandon)](https://github.com/KevinGrandon) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d2dea1661e2b)

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#BGgjI_VFTt6_OB-6qli45A

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by try-server-hook** [comment]
[KevinGrandon Kevin Grandon (KevinGrandon)](https://github.com/KevinGrandon) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2dc36c214deb)

**Pull request merged**
