### PR TITLE
Bug 1219678 - Impl number keyboard test suite in gij for keyboard app…

### PR DESCRIPTION
**Pull request by raylin**
quick fix for apps/system/js/input_window.js L35:36 comment.
squashed two commit into one.

…, r=timdream

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=00328fed6feea3a2b2a7d86aefdfa28bfa7a272f

**Comment by raylin** [comment]
I've closed other pull requests, and this is the latest commit. 
Thanks.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4428b771fdb5b9b2e2481aa0d30e31defeeca484

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=371f8b08cd39b7ac80e4f5da6858536b3560d98a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e358d821b574b10fc11d417a5f189e3e32220f8d

**Pull request merged**
