### PR TITLE
Bug 1181469 - Eliminate fb prefix from service_extensions.js

### PR DESCRIPTION
**Pull request by mancas**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b9fd1105f2158932c5411692867f5560f4b3a574

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e0f36f179d24b982f757897ae275e173fb1c970e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e0f36f179d24b982f757897ae275e173fb1c970e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e0f36f179d24b982f757897ae275e173fb1c970e

**Comment by borjasalguero** [comment]
Remove this as well from https://github.com/mozilla-b2g/gaia/blob/9dfedd7d35da00fa9b08dcffc3ab4f47da54e4f0/tests/python/gaia-ui-tests/gaiatest/apps/contacts/regions/contact_import_picker.py#L11

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=586b68de05a7d6ea431961d78deb9ea0d18c98a7

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d64b78b2a878f2c994df1ab88968e42105e0adea

**Pull request merged**
