### PR TITLE
Bug 1171998 - Implements Firefox OS version specific PDF viewer.

### PR DESCRIPTION
**Pull request by yurydelendik**
Uplifting https://github.com/mozilla/pdf.js/pull/5947

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1171998

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1eb7b6a2ecfb93b418e9e883313be9e2314c79c7

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a7d73e83387cc4548c48998a87ad424443b28f5f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ac91de7a92e38b43c51f0f5c0a63c55589d979af

**Comment by yurydelendik** [comment]
Closing this request as out-of-date. PDF.js project contributors re-purposed b2g code as "mobile-viewer" example. See https://github.com/mozilla/pdf.js/pull/7511

**Pull request closed without merging**
