### PR TITLE
Bug 1125095 - Task manager/tab view button tray polish

### PR DESCRIPTION
**Pull request by sfoster**
- Darker button tray for task manager card. 
- New light/dark assets for button images. 
- Tweak button/button tray styling to maximise hit area while giving consistent image size/positioning

### CODE REVIEW

**Comment by try-server-hook** [comment]
[sfoster Sam Foster (sfoster)](https://github.com/sfoster) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c0b5f25888dc)

**Comment by try-server-hook** [comment]
[sfoster Sam Foster (sfoster)](https://github.com/sfoster) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=253b79cfdce7)

**Comment by try-server-hook** [comment]
[sfoster Sam Foster (sfoster)](https://github.com/sfoster) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=61ccc3f2a4d3)

**Comment by sfoster** [comment]
Removed some meta-data bloat to get these images back down to reasonable size.

**Pull request merged**
