### PR TITLE
 Bug 1172902 - [Messages][NG] Use SimpleOfflineCache to cache all app resources. r=julien

### PR DESCRIPTION
**Pull request by azasypkin**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dcd657d55461e6fc6b05db15d1c935e7a259f823

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ab8471ea71cb835becded8766f7af49a9d2fe798

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c8f6338a8aaa26f5dc7223b1de4588ff07ae26df

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cda333157df40d82581f2ca93490571f960b0c6b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b42e548994dd3db4f93b1c43acbce772df6d6385

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0dfab0260bb1bd1bc4a2fc1731bff535b006d0fb

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=272b62940bf39ed298cd1d7881b50f2792f48a55

**Pull request closed without merging**
