### PR TITLE
Bug 1101772 - Music tiles should be in RTL order.

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[hfiguiere Hubert Figuière (hfiguiere)](https://github.com/hfiguiere) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=140b3f04b963)

**Comment by hfiguiere** [comment]
I have changed the PR to do what Dominic suggested.

**Comment by dominickuo** [comment]
tiles_rtl

Thanks @hfiguiere !!! This is exact what I mean in the previous comment, nice work. There is a minor issue where you can see the first 6 tiles and the second 6 tiles are not aligned left and right(margins), just fix it and I think this patch is good to go!

**Comment by hfiguiere** [comment]
That's weird, it only happens in RTL...

**Comment by hfiguiere** [comment]
Got it. the css rule should explicitly select on the direction otherwise they'll match a bit too much in "rtl". Updating PR.

**Comment by try-server-hook** [comment]
[hfiguiere Hubert Figuière (hfiguiere)](https://github.com/hfiguiere) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=13c0d1d08495)

**Pull request merged**
