### PR TITLE
Bug 1233823 - Make marionette-apps.launch wait for system rather than…

### PR DESCRIPTION
**Pull request by mikehenrty**
… homescreen

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=affebf915c532a0ee7c2597ca1fe9ee51577205e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1e0056cb536a397c48fb86362e749ca535fcc0ee

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=049206ed5f561be8a8b03edcc168c150d4e59a93

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b8f34d9364b2391c37001b9fe62d6c9906bbd732

**Comment by nullaus** [comment]
:+1:

**Pull request merged**
