### PR TITLE
Merge pull request #27965 from tedders1/bug-1112524-fix

### PR DESCRIPTION
**Pull request by etiennesegonzac**
Bug 1112524 - No longer dismiss dialog during attempted edge gesture. r=etienne
(cherry picked from commit b07ddbbf0f0a0d406404053da80703e9b55b870c)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7b7ce901ec02788c461054754866791f7c85060b

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=097af4095a24e7fb47777ddd540e25f830a56d50

**Pull request merged**
