### PR TITLE
Bug 1138778 - [ringtones] Don't resolve promises until indexedDB transac...

### PR DESCRIPTION
**Pull request by jimporter**
...tions are completed

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[jimporter Jim Porter (jimporter)](https://github.com/jimporter) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=fca6e90eb531)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[jimporter Jim Porter (jimporter)](https://github.com/jimporter) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=1e961ecc2c48)

**Pull request merged**
