### PR TITLE
Sfoster task manager no screenshot v2 bug 1107139

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dc6dd20cb165cfed23f3a2c0ae282f299e8baa78

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=25fe6beb9c320122e2b408057644020db3f55f5a

**Pull request closed without merging**
