### PR TITLE
Bug 1091441 - [Messages] the thread view is flashing while loading if there are MMS

### PR DESCRIPTION
**Pull request by steveck-chung**
- Use promise.all to scroll after all the mms contents parsed and attached
- Fix the chunk bug

### CODE REVIEW

**Comment by steveck-chung** [comment]
I understand your opinion, but I don't get why we need `TaskRunner` here. What benefits you could get from executing the append promise one by one? Using Promise.all and scroll to bottom while everything ready should be reasonable.

**Comment by julienw** [comment]
The issue is that when you use Promise.all, you wait for all promises before scrolling... that means that you don't scroll to the bottom right away to see the latest message.

On Flame I didn't see this was really an issue though, but I didn't try on Hamachi.

Aso, I think the pseudo code I outlined in my comment is more self-contained, I especially don't like this new property mmsPromises, that feels like another state we need to manage, and if we can avoid it, I think it's better.

But as I said, I prefer to land your patch than not land it, because it still improves the situation.

**Comment by julienw** [comment]
I just feel it will be more difficult to maintain; I can't really justify more than what I said about the additional variable, sorry :/

Can you at least try my approach and see how it works?

**Comment by try-server-hook** [comment]
[steveck-chung steveck-chung](https://github.com/steveck-chung) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=66bee7cd9671)

**Comment by steveck-chung** [comment]
@julienw TaskRunner WIP: https://github.com/steveck-chung/gaia/compare/message-reduce-flashing-taskrunner?expand=1 The main issue for TaskRunner idea is we could not display the actual number of messages for first chunk(If we want to keep the idea of showFirstChunk) Maybe be can move the message index checking inside the appendMessage, but we may need additional flag for the case when rendering ended with total messages less then chunk size.

**Comment by julienw** [comment]
here is the mail I sent to Steve about the Taskrunner WIP:


Remember that TaskRunner.push takes a function as parameter, not a
promise. The goal is to execute this function when the previous function
is finished.

So instead of :
```javascript
  this.taskRunner.push(this.appendMessage(message,/*hidden*/ true));
```
you can use :
```javascript
  this.taskRunner.push(() => this.appendMessage(message,/*hidden*/ true));
```

In showFirstChunk, you can just keep it like it is on master, because in
task_runner, we only put the function in the "then" callback. And it's
ok if a "then" callback does not return a promise or anything.

But you can also return `Promise.resolve()` if you want.

**Comment by azasypkin** [comment]
unrelated let's rename ```TaskRunner``` to ```TaskQueue``` please :)

**Comment by julienw** [comment]
yeah why not :)

**Pull request closed without merging**
