### PR TITLE
Bug 1155888 - Enable Join button on paste passwd R=aron.bordin

### PR DESCRIPTION
**Pull request by nrbrd**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e15576f4d95f9ee9f7d363296f66fe873d53e044

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9af6e48390e0d8733f3c62bad710488e7403182d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d513eb4036bd5c542e5d09590be37c56f87815c1

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=67474a5c350f7ff0c587b3eae844ab321e70838f

**Comment by autolander** [comment]
The pull request could not be integrated in as it contained a commit which was missing a bug number. Please ensure all commits contain bug numbers, and are in the format of: Bug [number] - [description]

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=26b0e875c1029de27a94aa724adfe2c8a733ea39

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#a5eZKjJcT4uKZsjph2UB_Q

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b0e6a18337bb5c1cf6f887fe40ddc71de4355710

**Comment by aron-bordin** [comment]
rebased on master

**Pull request merged**
