### PR TITLE
Bug 1211954 - dialer: RTL css refactoring

### PR DESCRIPTION
**Pull request by peppsac**
[Review on Reviewable](https://reviewable.io/reviews/mozilla-b2g/gaia/32270)

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e27551dc5aa56233fe949dd231aad641ab444469

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c3e078fbead2c30f4dfb3005bf2b0f40bfccaa2b

**Comment by fabi1cazenave** [comment]
@peppsac a unit test should be fixed before merging:
> TEST-UNEXPECTED-FAIL | null | [communications-dialer/test/unit/call_group_menu_test.js] Call Group menu Opening should display the good options and header

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ebb141a0f0ea1ad9987d8f35b0a39386947738b3

**Pull request merged**
