### PR TITLE
Bug 1164353 - migrate browser context menu to use smart-modal-dialog

### PR DESCRIPTION
**Pull request by huchengtw-moz**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5397099ddbe0c95158e682031b852fadfeba8e70

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0e9352e3b0250209d84c608caa777945d80592fd

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8c16e1822744b5945d11c7a292df295ad9f8e142

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6099516e1370e547c4124d97e40d63ac4225279f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e5fc56f8b6a91b81f585b810d46d647ef5d8afe3

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=020203aec58462d9ddaf498139b0910f4956dc3d

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete. You may need to rebase your branch against the target branch.

**Pull request merged**
