### PR TITLE
Update ro.js same settings for keyboard in 1.1 and more

### PR DESCRIPTION
**Pull request by raulmalea**
Update ro.js same settings for keyboard in 1.1 and more

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1f753ba3a91fa22579fce4c54ec2dc27f8efaac2

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by raulmalea** [comment]
Wrong request! Sorry!

**Pull request closed without merging**
