### PR TITLE
Bug 1174813 - siteIcon and webmanifest support

### PR DESCRIPTION
**Pull request by sfoster**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5a81979502efdc2119c1ad032b8fc8c3c4c0a95a

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ac9851881473860772efd1d17d596bd8d4d2b890

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7ba311f57538463796cdf12a95ebe6fc97ee744d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e8b96c1894d4a486fa61da8b1918d13cb7c98364

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cf428c80d9b3712481a53369cd888866cb7cdb41

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=aaac799db80a8e377a4d34dac6b4153ec949b71f

**Pull request closed without merging**
