### PR TITLE
Bug 1150495 - [GaiaGrid] Do not overwrite icons when we have a cached icon

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1150495

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e763fc8721dccde41d52401420d163314a69f8b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a1450858896cde43ac074c28a11367942c600456

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#R3GHoyZISXmmJuO7DAPDYA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=35f337cf02205e22860c1ce62f507e9bf12c7dad

**Pull request merged**
