### PR TITLE
Bug 1164354 - migrate app install manager to use smart-modal-dialog

### PR DESCRIPTION
**Pull request by john-hu**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=12eaec0d24064fc37e17113ded4b3faef0673d2f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cdbea37605cb08e3654d638de8cc53e2d272ebbb

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=871b0755b388cf7b26ee7750fff1e90a48e8832e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2ccec13d772bbddb0c8a1698f083ba6d63fa7900

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#ZdYc8QTPSwO8jKvXEHln6g

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7ce185926bad038998b2bf88527dcccb2970e46e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7d660ad2c99ae81084d6557752a59c71c1e55a5d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d3ffcbc6be682d3d1a63c0471217a7e88113676c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a071d9e827cb1a1b1ecb86dbf5ed4ea84503e1b3

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#nFJqwTNtTX6YbsnIwjNsrQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
