### PR TITLE
Bug 1126388 - Every input fields should be right-aligned in RTL language...

### PR DESCRIPTION
**Pull request by autra**
..., even if keyboard is not RTL

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[autra Augustin Trancart (autra)](https://github.com/autra) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=588603d65d24)

**Comment by try-server-hook** [comment]
[autra Augustin Trancart (autra)](https://github.com/autra) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2cf3efc96f72)

**Comment by try-server-hook** [comment]
[autra Augustin Trancart (autra)](https://github.com/autra) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d7aa9e7c4fa3)

**Pull request merged**
