### PR TITLE
Bug 1224656 - Test the search result updating.

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dda0b741b5c2f51e6a2ead5aaf1b6d56b2fcf25b

**Comment by hfiguiere** [comment]
Currently this test should fail.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7166da2c512be9221cceaf05e70a23d4a044f3d9

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=83f208fbf16b7c702ec17a48561cf065aed837a1

**Comment by hfiguiere** [comment]
The previous test would never have passed anyway. This version should.

**Pull request merged**
