### PR TITLE
Bug 1154607 - [System] make browser_context_menu as a base module

### PR DESCRIPTION
**Pull request by huchengtw-moz**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e0161e9e4f0cc732d4ec2eb1ca81cce2b64c8a02

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0360071e4ec9f03caff9c8da9bcc7366eeb45c29

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=23a1691f112a5d6d42a9127ca7fe147f2715b931

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dd9efcab4f0f156cd6262cddd50f7700cd558f8b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a8c49079e06975340f8e0c778bdd6fd2a5054a8c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=10d8b8766ee374a756df4cc0fb8f13e435203a11

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=52b57b0565800cd159860b7b5c9288f3ca163cc8

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=23be28a063004e8216876eb8c9a1d1162f2bd9bc

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8c29df16aaa6b6c536838f22c8a1f305b90dacf9

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9afd1d0d7a0799818bee72c340b41cb507ed662d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bb1d76266fdf9d3402153ce23e2621f46936cdf4

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete. You may need to rebase your branch against the target branch.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=70c63a28816e72233df29b587ba0ea545a696965

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b320ab38f5615d8e26db304f6188dc87fd4f307b

**Pull request merged**
