### PR TITLE
Bug 1159674 - Introduce NoSuchWindowException in gaia-ui-tests; r=davehu...

### PR DESCRIPTION
**Pull request by andreastt**
...nt

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3194ff8e01a66247469d0a4695b4e68aa69d886e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=28cdb7e5c316600cc3465a91efa6c8d99be30d3f

**Comment by andreastt** [comment]
Rebased.

**Comment by andreastt** [comment]
@davehunt: Looks like the tests are now passing.

**Pull request merged**
