### PR TITLE
Bug 1021173 - Report pre-installed apps in the FTU ping

### PR DESCRIPTION
**Pull request by marshall**
https://bugzilla.mozilla.org/show_bug.cgi?id=1021173

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[marshall Marshall Culpepper (marshall)](https://github.com/marshall) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c49ee34d8c96)

**Comment by try-server-hook** [comment]
[marshall Marshall Culpepper (marshall)](https://github.com/marshall) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e1f75cdb6fcb)

**Comment by try-server-hook** [comment]
[marshall Marshall Culpepper (marshall)](https://github.com/marshall) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f243684483af)

**Comment by try-server-hook** [comment]
[marshall Marshall Culpepper (marshall)](https://github.com/marshall) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c102f0427b22)

**Pull request merged**
