### PR TITLE
Bug 1144796 - [Settings] [Sound] Create ringtone screen text should not be selectable

### PR DESCRIPTION
**Pull request by punamdahiya**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[punamdahiya punamdahiya](https://github.com/punamdahiya) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=98692523cd5a)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=81a21433128bd29bbeb86d4304fc87f7412afc4e

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#e72bIlCrSMa3wsM5V5XK2A

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=37feb377b3bf709146334b25fea28aaf1cf08e67

**Pull request merged**
