### PR TITLE
Bug 1112131 - Updated gaia-header to v0.6.0

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[wilsonpage Wilson Page (wilsonpage)](https://github.com/wilsonpage) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f44b4331356e)

**Comment by try-server-hook** [comment]
[wilsonpage Wilson Page (wilsonpage)](https://github.com/wilsonpage) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=00ca39e27175)

**Comment by try-server-hook** [comment]
[wilsonpage Wilson Page (wilsonpage)](https://github.com/wilsonpage) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f411584d2f72)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[wilsonpage Wilson Page (wilsonpage)](https://github.com/wilsonpage) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=869d9d7c4ba9)

**Comment by julienw** [comment]
superseded by https://github.com/mozilla-b2g/gaia/pull/27959

**Pull request closed without merging**
