### PR TITLE
Bug 863501 - Support user playlists

### PR DESCRIPTION
**Pull request by errietta**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ca55e3d49966)

**Comment by hfiguiere** [comment]
Next time (no hurry, next time you update the PR), please use the standard commit message format. Something like:

Bug XXXX - What this does.

**Comment by hfiguiere** [comment]
Also it would be awesome to get test (with marionette) for each feature bits of the playlist.

**Comment by hfiguiere** [comment]
Also if I create an empty playlist, tap on the playlist, "Name" is displayed instead of the actual playlist name in the detail view. If I happen to play something from the artist or albums view, then when viewing the playlist details, it will be the name off what I'm playing in lieu of the playlist.

The playlist detail view is missing the menu to edit it. (see the visual spec that is attached to the bug)

There is also an empty playlist view in that spec (section 6.1 page 34)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=97a097e57c3e)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=552e638e69f3)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=806098e8c0d8)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=fcafaa591df3)

**Comment by errietta** [comment]
@hfiguiere where's the 'empty playlist' image?

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=630b7c58c0b6)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0e9b6fa3dff9)

**Comment by hfiguiere** [comment]
Things are taking shape. Nice.

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=1efad8dab5e8)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=47648d3e3adc)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=980f00891263)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=70fc9988e7ea)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=54a94a718f97)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=32e9b164567b)

**Comment by try-server-hook** [comment]
[errietta Errietta Kostala (errietta)](https://github.com/errietta) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ae340778869a)

**Comment by hfiguiere** [comment]
Two things you should watch out as the automatic tests are being run:

* the linter complains - easy to fix
* the playlist integration tests fail. That's serious.

(I'll test that later today)

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c46d94ffb01ddeae0ead133880c7d75a2dc3323a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9ad0ed78abd80c69b706b95604320c163ef95ead

**Comment by hfiguiere** [comment]
We landed the rewrite of the Music app we wanted for 2.5 - but we'd really love to get this feature for next year (after 2.5). Rebasing is gonna be hard.

The good news with the new app is that we have web components for UI which is something you expressed frustration over as it was lacking.

Do you feel like porting it over? We can help. Let us know.

**Comment by errietta** [comment]
Yes please ~
(I'm going to regret this aren't I ^^)

On Thu, 8 Oct 2015 02:48 Hubert Figuière <notifications@github.com> wrote:

> We landed the rewrite of the Music app we wanted for 2.5 - but we'd really
> love to get this feature for next year (after 2.5). Rebasing is gonna be
> hard.
>
> The good news with the new app is that we have web components for UI which
> is something you expressed frustration over as it was lacking.
>
> Do you feel like porting it over? We can help. Let us know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-b2g/gaia/pull/27125#issuecomment-146390783>.
>
-- 
Errietta Kostala
<errietta@errietta.me>

**Pull request closed without merging**
