### PR TITLE
Bug 1188139 - Refactor Music to use modern L10n API

### PR DESCRIPTION
**Pull request by zbraniecki**
https://bugzilla.mozilla.org/show_bug.cgi?id=1188139

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0a919f35e2e48771a164e383dc5b496a6ca53a10

**Comment by hfiguiere** [comment]
A couple of tests needs fixing too. There are a few oranges caused by these changes.

**Comment by zbraniecki** [comment]
will fix them today and request review :)

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4923b3a0fe45bf27c5b338561ac05e35cb10c9e2

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=259d6434d0d3351cdfb1d337e543738e768c7b5c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=766e599602b73da148bcf90e3df6b95c4bd4c42e

**Pull request closed without merging**
