### PR TITLE
Bug 1150587 - Intermittent text_selection_test.js, wait for system app in test setup

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1150587

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bca4e824f8f64358f00434426ccfb32d43312709

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#1lCbPwmkSReBR-ubftTXLg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
