### PR TITLE
Bug 1149024 - wait_for_notification_toaster_displayed needs 'message' as...

### PR DESCRIPTION
**Pull request by shinglyu**
... its argument

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1a3a8cd37336a8ce3bec58aa3287aed04972798c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1a3a8cd37336a8ce3bec58aa3287aed04972798c

**Comment by shinglyu** [comment]
@mwargers : thanks!

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1a3a8cd37336a8ce3bec58aa3287aed04972798c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bd81b49892d999d822027f6c4c5c9196f0a75ff4

**Pull request merged**
