### PR TITLE
Bug 1069619 - Browser menu button is not labelled

### PR DESCRIPTION
**Pull request by gopalmeena**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[gopalmeena gopal singh meena (gopalmeena)](https://github.com/gopalmeena) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0e639d6824f2)

**Pull request closed without merging**
