### PR TITLE
Bug 1156701 - Update download icons to be dark against white bg

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=509844aa52061eb91cb45560ba66946174e5ad58

**Comment by EragonJ** [comment]
demo

Mike, it seems that your icons are some inconsistent part that needs to be fixed. Please try to get a right one from UI, thanks.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c26a66f8a4fed4d5fa7af73d6e24dfa852108377

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8f29d8f38d97f1ff1fd25b21cb45f56064d3c061

**Pull request merged**
