### PR TITLE
Bug 1179040 - Don't hide setVisible(false) frames to benefit from gec…

### PR DESCRIPTION
**Pull request by etiennesegonzac**
…ko keeping the layer tree alive a bit. r=kgrandon

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=05ab9a846a743da67120538658ebafda67fd667f

**Comment by etiennesegonzac** [comment]
We're still blocking touch events otherwise you can scroll APZ divs while the app is setVisible'd(false)

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1098f8034ca858f70d87497a31cf63e4ee323d26

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5ea7b6a89c21fcc18d9690657d7ff54363c2f1f6

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e69442f124e6186b80ac0990e0c1027e0772f319

**Pull request merged**
