### PR TITLE
Bug 1136715 - Fix grammar issue in readme file

### PR DESCRIPTION
**Pull request by heavensmile**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[heavensmile Oliver Propst (heavensmile)](https://github.com/heavensmile) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=348ed8ec7c3d)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[heavensmile Oliver Propst (heavensmile)](https://github.com/heavensmile) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=dbe51f7fbcee)

**Comment by julienw** [comment]
landed in 3fad9f43d99b0ab7efaf712405285700d40f504a, thanks !

**Pull request closed without merging**
