### PR TITLE
Bug 1159092 - get ellipsis on the correct side for lockscreen and notifi...

### PR DESCRIPTION
**Pull request by davidflanagan**
...cation screen playback controls.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f44dd175f7bce23a4c83a5f0721c1eb576eae7a7

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=066001a7d539b871981ffb0da99ec9d5c834691d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d61b00e162402619fb2fb6d09c00b8b8d3442618

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=01a7df40df4ae2a5ef40a3f16b51ad56d5024f5c

**Comment by davidflanagan** [comment]
rebased and pushed again to trigger a new test run

**Pull request merged**
