### PR TITLE
[WiP] Bug 1225812 - Move setTopSites to placesModel, r=daleharvey

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=fff8b3e71aebad7051b2d44a7913ffc7e1f4f201

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=663282cef9102e1f877a12c605b1c86254f6c88a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=86a10abe5ec97749af4cbd1e95ceaacb7dd99870

**Comment by michielbdejong** [comment]
Cleaning up PRs that are > 1 year old.

**Pull request closed without merging**
