### PR TITLE
Bug 1158238 - [System] Add import activity

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1158238

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=22908eeacb8d5e1fba19274a2dd8ce3c5e182f60

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c13d8bde85892adcaed5eee8032670cadc5c0c6f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=21b780fd13a8a4835d17838ad7c22f987120ba1b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1ffd798bcd026ef79c455dd34f36d416c2469969

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#LEo1pnbeR9yybylF3KAI-w

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#Xhqva16VSIui0j4XyIZxUQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
