### PR TITLE
Bug 1217713 - Add simulator code to MultiWindow for Simulator. r=schien

### PR DESCRIPTION
**Pull request by mantaroh**
https://bugzilla.mozilla.org/show_bug.cgi?id=1217713

This PR is in order to get the feedback.

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cfb5932f7c4d5c82af75bf8128b4bf06eb9ceb68

**Comment by KuoE0** [comment]
HI @mantaroh, could you wait for [Bug 1235123](https://bugzilla.mozilla.org/show_bug.cgi?id=1235123) to fix? It will change the architecture at Gaia side.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6c568fe2d58b855342e0dcc9ef201dacb2ad83ef

**Comment by mantaroh** [comment]
Thanks Tommy.
Because I've got the feedback from you, I will close this PR.

**Pull request closed without merging**
