### PR TITLE
Bug 1300279 - New init logos for B2G OS r=fabrice

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cb93afea66cb53acf7f7c63bb9801d630ff6264e

**Comment by lissyx** [comment]
Please change chmod to 644 and not 755 :). It would also be cool that you make another PR for the boot animation :)

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a5afba90ebda7c02e6c94906b74a487c5ce3ff91

**Comment by kskarthik** [comment]
Done!

**Pull request merged**
