### PR TITLE
Bug 1227577 - Develop a new marionette-client promises driver r=gaye,auswerk

### PR DESCRIPTION
**Pull request by andrenatal**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9c36f67955a8d60c07a74b965fac952fb9141f3c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3a05550d15476353102d0e338c3e61d30530e62d

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b538f3185db7730331fe086322ff67522ceb2dc3

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=abbecfd2ee7e658a9d5fd082140d5145f3bd7b3e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5964c96024186a14356e0e470500b6f737fdc8de

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ac4c36c663c893c6c85d782ee614edd04848442e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=282462fcd6271a3afdbe2cf6b8f23b43435f5e58

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=378be3d1dee23e0daed1d60b4e7dd10e4542352f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9a56c84565d8a560e90569acec0af7dac02a9d36

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ee422ad0caf1bbdf8f1bac188ecf6951daec5aa5

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8ab62d1a95921bac31967519e612884b5550d935

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=566f29e34833531ba15a309f2042289d106d2a86

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d477305d90205b78933308172027dc9ae9350f9c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6818c92c4ee522e37dd417f2788a2114892c0c86

**Comment by andrenatal** [comment]
@nullaus @gaye One weird situation here is that one of the unit tests always fails on taskcluster while always pass locally. There is some way to exactly reproduce their environment to understand why this happens?

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c0364291c762d1b053583b64d3aa70432cbc6229

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=18f70ecc15b2d961228e97bf3779dbf2d260af60

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=227137927e830144e1dd2e07c3c8b4ec73747b2c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e7ef2825261ba9baa3188c6970f092ea5a9307b2

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5bb9c526b30e0912e3702f259af593c5fa12b46c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7e04398d50818b27df5794b3d6264f1604bb46cb

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c2be6df70aebed412e86966f4fb2a2788d2006df

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5baa158e1eaeb213704c407132283e73712c0d39

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e22d14ef4b1548296b2b46bcc2b3568b5be08cd

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e03f82d5c12a7c7618b74d09c0d56703b75fdc1d

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8bf2329a5f824947dfd5fca35a9065b8b808b29b

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5865338de26e04fa2561c6522d386e2633522224

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ab8d03b33261dd071dbdffb6d7a198f413d25259

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=191bc613ff009490b8408ce0e0dd75b41a84f0c1

**Pull request merged**
