### PR TITLE
Bug 1168061 - Moving statusbar icons HTML to each icon file r=alive

### PR DESCRIPTION
**Pull request by albertopq**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ececfded34df82fe1e1fb7c275caf5891d0b4164

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f2a2e5cfa400bccf7c976963a451071619e95f89

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8769f4fe5f7c8a961b6b6d52972d314448ddac84

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#YFZqTAugThGypQF1_nXLOA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#QhdDgltlRuOxx-GSC18sDw

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8769f4fe5f7c8a961b6b6d52972d314448ddac84

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=67577ed96be9633d753e9871bbea281dddfc3cbb

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#a7IKXapwT8a2-AwLVl-d9w

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a67d31e9c2223206c5d0d4b678cebf1523280ab3

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#zosqZAZMQQ6cDFcRwRfDOg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=17d0f4d32d240ab1395f27c0a39b97bdc8862647

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=430dcf8ac5e34f755c2cbc8cc124e105f5ab70eb

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1eaf65ee2cb328bfabb002a3030dfaf1caaa60e4

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#r-Q1420KQyuCGZbvSCA1RQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d9f629386fc3e726b320b23c5d7b033175669433

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=31bde6ba371ec2c0637e91f9ba5556b05a4e2947

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f6a392a93b50811da1e9b26e06dc7064ed0489a5

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b48894d887286da2168018468c1e17b271c54983

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#PwUEpV4RRmqDy7YZAT3yxg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b48894d887286da2168018468c1e17b271c54983

**Pull request merged**
