### PR TITLE
Bug 1100995 - Do not attempt to localize undefined strings when clearing the suggestion bar r=thills

### PR DESCRIPTION
**Pull request by gabrielesvelto**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=94e4da543696a63cc249163d781cde118e111952

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f3403ec5f758ce9861a80ec740e928b2a1d1222c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=98d3ed65a1161ed397f03f6a4620beea179cd232

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=679d6579126bd5a7dddd3afaf630697e286505e1

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete. You may need to rebase your branch against the target branch.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=69cb581d7c8ee8c2ebc98a5dd444dcdc26b4e1d4

**Pull request merged**
