### PR TITLE
Bug 1140315 - [Search] tapping 'No internet connection' is easy to trigg...

### PR DESCRIPTION
**Pull request by gmarty**
...er search engine setting when offline

### CODE REVIEW

**Comment by try-server-hook** [comment]
[gmarty Guillaume C. Marty (gmarty)](https://github.com/gmarty) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2f2f07d1eaf3)

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#WcH8GfG9RTOBGyQVidwlFQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cb7f6f1070489bf5ae79920fe2b13739ea9ef9b2

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cb7f6f1070489bf5ae79920fe2b13739ea9ef9b2

**Pull request merged**
