### PR TITLE
Bug 1146804 - Create file front-end for word_list_converter.js

### PR DESCRIPTION
**Pull request by mnjul**
xml2dict.js can now perform the function of xml2dict.py. It requires node.js (as does Gaia build environment), and xml2js npm package.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4a7425f6ee3297ff543ebe63ddabaab050d8c95b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4228e0c912e2f04ebccb3f39fd83600b2039a447

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d5d89d34edcd824e493af9b44741c6eabbd6086e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9266833fb2806058a3fe6eed06f2a206e9ebfaf9

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=268b3299526e7ea0975aff2eb6ec87ceb9703483

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c6818965dcdf3b8c9c0d17582f0fb30870779a5f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ee82f6ce37d2b1020f048bb937ced2049c300be2

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#VVUhKxRBTMyt5XRMWAyAwg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
