### PR TITLE
Bug-1105035: Don't raise gesture panel in fullscreen mode. r=kgrandon

### PR DESCRIPTION
**Pull request by tedders1**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[tedders1 tedders1](https://github.com/tedders1) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=9558a04abfc6)

**Comment by try-server-hook** [comment]
[tedders1 tedders1](https://github.com/tedders1) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4e20f061f60e)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[tedders1 tedders1](https://github.com/tedders1) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=6ac87ee5bd8c)

**Pull request closed without merging**
