### PR TITLE
Bug 1152230 - ellipses sides

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=00fb65045e61077f3df3063b1b1e61c6266868b5

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=00fb65045e61077f3df3063b1b1e61c6266868b5

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=014ea08001cb2281d9d84e18a8043a121aed5c94

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=016d75c0f198353038835b7afb0829989058b436

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0458946ff74a7917957e302b70e18b665cf6b683

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=face69af9925f6e89d67c6d62af1f85f9a3d74f2

**Pull request merged**
