### PR TITLE
Bug 1127318 - Contacts with only a last name and a phone number in Gmail...

### PR DESCRIPTION
**Pull request by yvtheja**
... will be displayed as {phoneNumber} {LastName} while importing contacts from Gmail

### CODE REVIEW

**Comment by try-server-hook** [comment]
[ythej Vishnu Teja (ythej)](https://github.com/ythej) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=710d7f6e16c5)

**Comment by try-server-hook** [comment]
[ythej Vishnu Teja (ythej)](https://github.com/ythej) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=17147364d8b3)

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete.

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete.

**Comment by try-server-hook** [comment]
[ythej Vishnu Teja (ythej)](https://github.com/ythej) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=addd12711269)

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#Ei4kqXLzR22CJmeJ9_pYzA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
