### PR TITLE
Bug 1183941 - Create son_wordlist.xml

### PR DESCRIPTION
**Pull request by Afudu**
This is for follow up of Bug 1183941 - (Songhai-keyboard) Add Songhai (son) keyboard layout

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7ace9e7d2f5a935ac0a8b7feda913ef0e7d8ef0b

**Comment by Afudu** [comment]
Bug 1183941

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7ace9e7d2f5a935ac0a8b7feda913ef0e7d8ef0b

**Pull request closed without merging**
