### PR TITLE
Bug 1052227 - Move inapp pay test to packaged to avoid mochitest failure...

### PR DESCRIPTION
**Pull request by ferjm**
...s. r=kumar

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b5bd2cf26d1f617cf1d193b356a7ce68356e9fb7

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c3eac06c11a609f185e4fd5228b34657e067a7fb

**Comment by kumar303** [comment]
Thanks. I think this will be easier for maintenance.

r+

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1c21572463ba5e7efae0f041e4a6d379a88eac78

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=90372e089b8e8e5f58220780be65cae8806298dc

**Pull request merged**
