### PR TITLE
Bug 1155901 - Dynamically resize the 'call ended' string whenever it's translated

### PR DESCRIPTION
**Pull request by gabrielesvelto**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b5ef159d4554efcf4cd6ca9742653f6645114d5e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7735ec62417ea6a1ad7c5030bf023023d1555d22

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a543d7720cbd254710b235858624888b903a5a06

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a7a0b1c58ee28a32f2a752ac6f47b18ded6b1723

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=12ca209f67576e422e00ac84be155748dde58ca0

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8a12b65c342b902b35df279927c369691c5c9add

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c3fe633f4cc9d8aed950496439e0f72458031b01

**Pull request merged**
