### PR TITLE
Bug 1192171 - Part 1: better test createDCFFilename

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=279267fc55d3220cb20bd156df86ca65aaef1535

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6775b69e7a967ac59548775388a939d99fd9282d

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3eb68d861fa2176cd485f6e8968bcaf7347d0a39

**Comment by hfiguiere** [comment]
Closing this. I'll move it to a different bug.

**Pull request closed without merging**
