### PR TITLE
Bug 1190859 - [META] Make settings.html a self-contained view

### PR DESCRIPTION
**Pull request by fcampo**
... to be merged over [1190859 - Make list a self-contained view]

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=814f1a2734b2243eec31bb107704c44efc3104a8

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5c69e0eaa7d4bf824b07141aa6e179df07fb3510

**Comment by arcturus** [comment]
Great, this PR will allow me to test first the list, and later come back to the functionalities in Settings.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=106315d77f4273d355ab000fbb57ac3c054fcf94

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=389bdd82e5b3788af0e65c05702d0bb4909ec2c4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b7345b560b293d7635b65799891772926b455818

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=498a37ee0c94fafcd1fbeda36b01a35945ab36df

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0d5e62cda3d92802ec18aebb3b301a17d2da9ec7

**Pull request merged**
