### PR TITLE
 Bug 1168941 - [Messages] Conversation view is rendered incorrectly when user tries to send message from Participants view. r=julien

### PR DESCRIPTION
**Pull request by azasypkin**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e86c4d17a5148dce79162fcfd7901124869948f4

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ae11f4990c0b2f1adc558507ba92190b1c1f0112

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d0431c5631cd459ee3574137f7d8edded7520337

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d68b12583cc2c7807a485fde724bf113a432a893

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9fadd43adeca5310c2eb40ed8c52ba9d192a94d1

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#4z-L1fXgQR2ePERW1PCFmQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#C3P6zxk4S6iqMnIrX3bHdw

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
