### PR TITLE
Bug 1118361 - Detect end of status bar fade using transition events instead of comparing computed style

### PR DESCRIPTION
**Pull request by birtles**
This obsoletes PR 27185

### CODE REVIEW

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d1d1fb0bfa3e)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b3cd948e77b6)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4f4c3da7805f)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f0893b49ddbd)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=a28ef8750db1)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=56d5366537e4)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=042387f80102)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2ff80ec4ef57)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=44db36db4130)

**Comment by try-server-hook** [comment]
[birtles Brian Birtles (birtles)](https://github.com/birtles) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=69a7acecbc80)

**Comment by birtles** [comment]
Replaced by #27336

**Pull request closed without merging**
