### PR TITLE
Bug 1152591 - Stamp bower.json with new gaia-theme

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1152591

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=17282551cccc751d4f3d6208ab45e7d7e613e5be

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#aqywiNuIRDWV-H6rzVUeuQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#Brp-F3E1T6ig3jOJ-8cj5A

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=850866b8e7858c18609b4eacc4926e84b76a3c88

**Pull request merged**
