### PR TITLE
Bug 1161990 - [Stingray] Write content of folder immediately when fol…

### PR DESCRIPTION
**Pull request by dwi2**
…der changes

https://bugzilla.mozilla.org/show_bug.cgi?id=1161990

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a541b810cb6b3dda1012a79c9e67f75811cef205

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#AqE3XfnVS-e4z1CNWwS5XA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#zgQ7_K7ARI-c_yFsINa3Mw

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f04d88d9657db9380e66416d6408b998f60fc5e0

**Pull request merged**
