### PR TITLE
Bug 1168814 - Disable the toggle for sending performance data when dog fooding r=eragonj

### PR DESCRIPTION
**Pull request by crh0716**
https://bugzilla.mozilla.org/show_bug.cgi?id=1168814

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3b39a1c16aac3151ac1d16636cdcef7f1cfad60a

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a35fa529b50178b6160d295d7dc81dff51d56d04

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#Onz3Rz0FTpmh-5tGYyYu1Q

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#ra11QxcQSnSYpcdP2H2u5Q

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
