### PR TITLE
Bug 1110660 - SIM2's PIN1 code will not pop up if SIM1 is not locked

### PR DESCRIPTION
**Pull request by YangYangSPRD**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[YangYangSPRD YangYangSPRD](https://github.com/YangYangSPRD) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=522eef02376a)

**Comment by try-server-hook** [comment]
[YangYangSPRD YangYangSPRD](https://github.com/YangYangSPRD) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ffc29cb1610d)

**Comment by try-server-hook** [comment]
[YangYangSPRD YangYangSPRD](https://github.com/YangYangSPRD) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e4c71d2952f0)

**Comment by try-server-hook** [comment]
[YangYangSPRD YangYangSPRD](https://github.com/YangYangSPRD) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=21d218c217e2)

**Comment by try-server-hook** [comment]
[YangYangSPRD YangYangSPRD](https://github.com/YangYangSPRD) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=9a5f5f588525)

**Comment by try-server-hook** [comment]
[YangYangSPRD YangYangSPRD](https://github.com/YangYangSPRD) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=673fa0d2844f)

**Pull request closed without merging**
