### PR TITLE
Bug 1074117 - Use expected conditions and optimise element lookups in phone app object

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7f40f8629a30)

**Comment by bebef1987** [comment]
Started adhoc job:
http://jenkins1.qa.scl3.mozilla.com/job/flame-kk.ui.adhoc/564/

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5979c2ba38a0)

**Comment by bebef1987** [comment]
restarted the addhoc run http://jenkins1.qa.scl3.mozilla.com/job/flame-kk.ui.adhoc/585/

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5149369d472f)

**Pull request merged**
