### PR TITLE
Bug 1125798 - Investigate camera switch source failure on automation

### PR DESCRIPTION
**Pull request by bebef1987**

### CODE REVIEW

**Comment by bebef1987** [comment]
http://jenkins1.qa.scl3.mozilla.com/job/flame-kk.ui.adhoc/663/console

**Comment by try-server-hook** [comment]
[bebef1987 Florin Strugariu (bebef1987)](https://github.com/bebef1987) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7602b156bfd7)

**Comment by bebef1987** [comment]
http://jenkins1.qa.scl3.mozilla.com/job/flame-kk.ui.adhoc/664/console

**Comment by try-server-hook** [comment]
[bebef1987 Florin Strugariu (bebef1987)](https://github.com/bebef1987) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c8a5b25954af)

**Comment by viorelaioia** [comment]
nice fix, green adhoc :+1:

**Pull request merged**
