### PR TITLE
Bug 1176905 - [FTU] Convert checkboxes to use gaia-checkbox

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1176905

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=31b239b02efa38438cb18e432be42bc3f95a4eea

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a794bf1a777f932504a93b3d4d7d7ffb0c250d46

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0efcb2b9d48337f804dfd73be03222ba25770fa7

**Comment by KevinGrandon** [comment]
Try run: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f624cf0eec72

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=22e2945aeb74e46ac58213c7a9bea8928aef9d11

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=540701791684cc527dccc9b7f1d4b694c7ce296f

**Comment by KevinGrandon** [comment]
Try is a bit red after force pushing, but was green prior. I think we should be good to go here, so going to land.

**Pull request merged**
