### PR TITLE
Bug 1222180 - Fix error message for contacts who lack a phone number or email address

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2258b366266cb75ea530ddb7bee81400c7eba056

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6684bf007c52b6b7aa76116ea7b4d45765276a97

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a721d686b614509962610c458acff743a06653e9

**Comment by kumarrishav** [comment]
No need to indent others. One more thing, try to grep the older key and value (string name n value),  to check if it's used somewhere. I guess it must be used in unit test to match the string. If yes then you have to modify there also.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=28c27d0814d300aeef51c205803739be817cc427

**Comment by comzeradd** [comment]
@kumarrishav PR updated

**Comment by kumarrishav** [comment]
Thanks for patch. Set feedback request to me on the patch in bugzilla. Will look into it today.

**Pull request merged**
