### PR TITLE
Bug 1207485 - Remove mozChromeEvent/mozContentEvent w/ new InputMethod API methods

### PR DESCRIPTION
**Pull request by timdream**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e262b04c7cc02094e181988d76949bc5fa986be5

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4144cd0c5664c257aacca3ca1267d9da29be65ac

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=72f36b3dd21af8c4b61cfddc00adad57bfd46286

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0ea6e2bf507c7d1446222e70f6a23b6950cda085

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e93c6982f3170a6d7d53e9dfdff41fd1c569f564

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=301e05b3b8f0dc618a69596d2f5fe757c36cbde0

**Comment by timdream** [comment]
Going to rebase and merge in another pull request.

**Pull request closed without merging**
