### PR TITLE
Bug 1176657 - Fix confirm dialog when importing vCard contacts throws…

### PR DESCRIPTION
**Pull request by mancas**
… an error

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=74163e14310c3f09560d333d49547cdc19fb786f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=74163e14310c3f09560d333d49547cdc19fb786f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=74163e14310c3f09560d333d49547cdc19fb786f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=74163e14310c3f09560d333d49547cdc19fb786f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e325c1b43766989297550a433fce03a77f559d28

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=55e0d8b8e105f542bb26dec26336bf1e20498dbc

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e9cca1ce064acf84dca0f7fec1eef6c29d3cbc04

**Pull request merged**
