### PR TITLE
Bug 1168014 - [Stingray][EPG] Align program titles in the first visible column

### PR DESCRIPTION
**Pull request by sean2449**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4382dee9806d64dd33c0dfa7eca9333df03d4a06

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a3f56ab047069edf55c7b920c861147d48deaf20

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b4083ee4a76f48ad023e500b4d6733950a89e7b0

**Pull request merged**
