### PR TITLE
Bug 1149070 - [Text Selection] Right caret disappeared in email select all

### PR DESCRIPTION
**Pull request by jrburke**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7220c0c7efdcc2aa29ae149d28a0dce490e9a008

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f569b3ab8240a2c59566a350ba5dbe5b590492df

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#4kC8OrlSTYafEUH6TamOyA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ebea27bc49e23dc21a55873a29ace1b931ae10d9

**Pull request merged**
