### PR TITLE
Bug 1140339 - [Messages][Tests] Add integration tests for sharing drafts between two app instances. r=schung

### PR DESCRIPTION
**Pull request by azasypkin**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=40a159d15c3b)

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=45fa57cbfb5e)

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=3e7f0bd6f309)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=65caf807a3065cac7804b9475757db92eaace78a

**Pull request closed without merging**
