### PR TITLE
Bug 1020699 - Remove header mutation obserber from font_size_utils.js…

### PR DESCRIPTION
**Pull request by mikehenrty**
… now that we have gaia-header

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=14073ca6a9b0a3225740b0196a4713904e909ce1

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5a9485ec907f37ff0234b8836a9dc0d2def69a82

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=38c6691d121a2e64274f7ecd883950643221f009

**Comment by julienw** [comment]
I think nobody (besides email which uses its own copy) uses `getStyleProperties`, `getWindowWidth`, `getContentWidth`. We can remove this as well, right ?

**Pull request merged**
