### PR TITLE
Bug 1120577 - Privacy Panel, RPP retry count

### PR DESCRIPTION
**Pull request by fabi1cazenave**
https://bugzilla.mozilla.org/show_bug.cgi?id=1120577

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[fabi1cazenave Fabien Cazenave (fabi1cazenave)](https://github.com/fabi1cazenave) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e330273d85b4)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[fabi1cazenave Fabien Cazenave (fabi1cazenave)](https://github.com/fabi1cazenave) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=45f2273bebe6)

**Comment by try-server-hook** [comment]
[fabi1cazenave Fabien Cazenave (fabi1cazenave)](https://github.com/fabi1cazenave) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=64984c8ce66f)

**Comment by try-server-hook** [comment]
[fabi1cazenave Fabien Cazenave (fabi1cazenave)](https://github.com/fabi1cazenave) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7657a7c32503)

**Pull request merged**
