### PR TITLE
Bug 1130011 - Removing superfluous touch event listener on the whole window r=kgrandon

### PR DESCRIPTION
**Pull request by etiennesegonzac**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[etiennesegonzac Etienne Segonzac (etiennesegonzac)](https://github.com/etiennesegonzac) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c6d63b6945a1)

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete.

**Comment by try-server-hook** [comment]
[etiennesegonzac Etienne Segonzac (etiennesegonzac)](https://github.com/etiennesegonzac) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=899955b3b6b8)

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete.

**Comment by try-server-hook** [comment]
[etiennesegonzac Etienne Segonzac (etiennesegonzac)](https://github.com/etiennesegonzac) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b8f81e51a460)

**Pull request merged**
