### PR TITLE
Bug 1202449 - FxA promises

### PR DESCRIPTION
**Pull request by michielbdejong**
Work in progress

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=35bfcddb58c6f07474ca911bf59b1dfadd388e67

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6a99c4e5192f906475866f3201061ec072279bd6

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=63bf1a40d32d626ed6f98280dfa3026e39e551c4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=28cc963f79a9aa1f24b9bb14cbc7e23dd764a618

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4d8e527acdb2ddfbb5c1462bfeef50e8a9548669

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c1210f9059e964d96bce6db7a53cbbc4676e30bb

**Comment by michielbdejong** [comment]
I did not change `shared/js/fxa_iac_client.js` since it's used in quite a few apps, this is refactoring just inside the system app.

**Comment by michielbdejong** [comment]
Oops! Just realized that e.g. https://github.com/mozilla-b2g/gaia/blob/master/apps/system/fxa/js/fxam_server_request.js#L39 still relies on https://github.com/mozilla-b2g/gaia/pull/31798/files#diff-d83266d4c6b27941574a0ba0306acd82L73 so I can't refactor one without the other. Will fix!

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9c64c4394774de168fb3839e8e8d3291dbd0cf10

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=45b9d92be7d776d26f9c174a68abc9468b3ec82c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0e42933f6c5779a7e1fe44df9421d839b80ab734

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=221a8c94ca0604efab0f1b4cc8ff228f42f667b9

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=69de78f1ad14cec856247f362ecc0bfb33dd3656

**Pull request merged**
