### PR TITLE
Bug 1172699 - Migrate timeIcon to Intl API

### PR DESCRIPTION
**Pull request by zbraniecki**
https://bugzilla.mozilla.org/show_bug.cgi?id=1172699

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=46d859e8db5bc28d207dbee266675f0634f30792

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4ac7ac0633170834e825f0c35ae654c3a8efc1c7

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ed6f03172680c754a96ec90cb98cfcd85944cafb

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=30eadbe7c37d151ccd95fe32407afbd96df3ada2

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4037a37a09389a2874db7e56678fee473cbb677b

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=fc15f4f36bae44ff35ea4a30917dc8c7bf7b424b

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=36827542237b90edc3e8f9c226b6e82e4d5e4014

**Pull request merged**
