### PR TITLE
Bug 1122597 - Remove unused search geolocation call +autoland

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1122597

### CODE REVIEW

**Comment by try-server-hook** [comment]
[KevinGrandon Kevin Grandon (KevinGrandon)](https://github.com/KevinGrandon) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=99c7fa6f1595)

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#lc77pfmCRlmca05DpbbAOw

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#hvAeRUsAT8qUbZXqVPAKrA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#KaAUdp8KQjyf1cifHd3Log

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by try-server-hook** [comment]
[KevinGrandon Kevin Grandon (KevinGrandon)](https://github.com/KevinGrandon) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b0a7b79d20a4)

**Pull request merged**
