### PR TITLE
Bug 1142448 - Use the date format in the localization file r=eragonj

### PR DESCRIPTION
**Pull request by crh0716**
https://bugzilla.mozilla.org/show_bug.cgi?id=1142448

### CODE REVIEW

**Comment by try-server-hook** [comment]
[crh0716 Arthur Chen (crh0716)](https://github.com/crh0716) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e0758284c71e)

**Comment by try-server-hook** [comment]
[crh0716 Arthur Chen (crh0716)](https://github.com/crh0716) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f0dc3640f825)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=fd88e8d069f09f77624b530e5f4df8e9ddd66cd3

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1b2973173068fa7f5ef99482b2e3d01ad4450882

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#ow0LjYL4T7qXAM-K-OSbqQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5f48e130a747effb49131816fb0a3c03fa1f7942

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#TRKKL8uaQhuEDq8xd7qkVA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8cf74d3c560c44c4c9254bb64d280dc9337bb585

**Pull request merged**
