### PR TITLE
Bug 1167638 - WIP

### PR DESCRIPTION
**Pull request by etiennesegonzac**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4bb969b3bc6617d3c1a9b2a10eefd8901a6c0eaa

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4bb969b3bc6617d3c1a9b2a10eefd8901a6c0eaa

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=24155d17dd72315242cbb8912ecf436d3ad77249

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7ae04bb99c296a2a6ccc26e6630555e53dee493c

**Pull request merged**
