### PR TITLE
Bug 1142591 - Wrong number of contacts imported and merged shown in the ...

### PR DESCRIPTION
**Pull request by adrm**
...banner when importing the contacts from a multiple vcard

### CODE REVIEW

**Comment by try-server-hook** [comment]
[ADLR-es Adrián de la Rosa (ADLR-es)](https://github.com/ADLR-es) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=6e6746c9dc15)

**Comment by try-server-hook** [comment]
[ADLR-es Adrián de la Rosa (ADLR-es)](https://github.com/ADLR-es) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f50e36177f48)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f009f5b61bf8dd7cae496079a4d379c57a1e5677

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f009f5b61bf8dd7cae496079a4d379c57a1e5677

**Pull request merged**
