### PR TITLE
Bugs 1112131, 1124582, 1127857 - Use gaia-header 0.6.x r=julien,wilsonpa...

### PR DESCRIPTION
**Pull request by julienw**
...ge

This changes how gaia-header calculates the font size to squeeze the header text
in the available space. We don't use offsetLeft but instead we calculate the
various buttons widths. In the common case where we only have the action button
we don't even take the current width and assume it's 50 px, which eliminates a
possible reflow.

Additionally we now support the start, end, and no-font-fit arguments.

start, end: allows the component user to gives the left/right button sizes to
the component, which effectively eliminates all reflows.
no-font-fit: when this attribute is present we skip all font resizing algorithm
and thus no reflow. This allows to defer some initialization (and reflow!) for the headers
that are not displayed at startup.

Last but not least now we try to squeeze the font fit for centered titles before
uncentering them.

(cherry picked from commit d13597bc73c07d0c496a3ab092c95b99c31cebfc)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[julienw Julien Wajsberg (julienw)](https://github.com/julienw) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=71eb254bc449)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[julienw Julien Wajsberg (julienw)](https://github.com/julienw) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ee5bbf5c4fe3)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[julienw Julien Wajsberg (julienw)](https://github.com/julienw) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=381304964649)

**Pull request merged**
