### PR TITLE
Try new isolated worker type

### PR DESCRIPTION
**Pull request by lightsofapollo**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6b0cfd2b99d1adf9c5bb172f337367f0c05e8300

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2132687563bf7b8c4b588b0650b91cc6826820e9

**Pull request closed without merging**
