### PR TITLE
Bug 1159028 - [music] Refactor the music database backend (part 1); s…

### PR DESCRIPTION
**Pull request by jimporter**
…econd take: fix share activity

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6d6d95fc82e245e3e8957c8329d2e61e8991acb4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6d6d95fc82e245e3e8957c8329d2e61e8991acb4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6d6d95fc82e245e3e8957c8329d2e61e8991acb4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6d6d95fc82e245e3e8957c8329d2e61e8991acb4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6d6d95fc82e245e3e8957c8329d2e61e8991acb4

**Comment by jimporter** [comment]
I'm going to land this, even though I'm getting random purples. I'm confident that the code is right, and the tree is open (and all the tests seem to actually be passing, too, if you ignore the purples).

**Pull request merged**
