### PR TITLE
Bug 1152774 - [CI][Unit tests] Waiting for server on port 8080 failed.  ...

### PR DESCRIPTION
**Pull request by julienw**
...r=lightsofapollo

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5e519aae424be7d58940eb36387a68ee04451d7c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=214641158adabb31d2be26048b574497ac7158dc

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=46a84c39f166fffc3bcb1af3548a8f9292a95886

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c513c4c35c1a817c562bb57f961fae7ba73519a9

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a93870eaf5a5d8d2819b64b4b59b69cb26cfa899

**Pull request merged**
