### PR TITLE
Bug [1033185 ] - [Persian keyboard]. Test two persian keyboard

### PR DESCRIPTION
**Pull request by Thatoo**
Bug [1033185 ] - [Persian keyboard].
I would like to test two layout of Persian keyboard on https://github.com/timdream/gaia-keyboard-demo

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=539f3e59939875154dc8fab73a4bbdcba40249de

**Comment by Thatoo** [comment]
I would like actually to try them on my Nexus 5 FFOS 2.5 spark build by Vosky, http://forum.xda-developers.com/google-nexus-5/development/nightly-firefox-os-t2960953 , but I'm a bit lost how to do that.

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9d43ea9d72a259dd24a06b17ba525631cec5ae0d

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7164c06b8e1a2641b48bbc33158dc5d9011cc903

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=43d46575a646cb7a4bdee5d2955606adf2f0450d

**Pull request closed without merging**
