### PR TITLE
Bug 1153873 - Bump marionette_client dependency to 0.10

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4b4a7d60231bae9d128dcffe8d2fefabba2a190e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4b4a7d60231bae9d128dcffe8d2fefabba2a190e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4b4a7d60231bae9d128dcffe8d2fefabba2a190e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4b4a7d60231bae9d128dcffe8d2fefabba2a190e

**Comment by davehunt** [comment]
@geoelectric it looks like taskcluster is combining results in treeherder. We need to land this ahead of an upcoming server side change, if you could review it soon that would be great. Thanks.

**Pull request merged**
