### PR TITLE
Bug 1152986 - Contact Last Name is repeated in Name field when viewing a...

### PR DESCRIPTION
**Pull request by adrm**
...n attached vcard with Last Name and without Name fields

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=09125042a907f4d2a534c7885eb1e18c7b361666

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=09125042a907f4d2a534c7885eb1e18c7b361666

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=09125042a907f4d2a534c7885eb1e18c7b361666

**Comment by arcturus** [comment]
Closing since it's done against a really old gaia version

**Pull request closed without merging**
