### PR TITLE
Bug 1162131 - Pin marionette-driver to 0.5, r=davehunt

### PR DESCRIPTION
**Pull request by jonallengriffin**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4c9d80602bef386fe5cc409630afb93a210deca2

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0b3d634a77523762fb7ec1075382c960168618f5

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=34bce0d1a4b6b50738731d0ff70e128a568626a7

**Pull request merged**
