### PR TITLE
Backport tc

### PR DESCRIPTION
**Pull request by lightsofapollo**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=75d7ad099f4b8367ca3009b11c6bd8efb14614ef

**Comment by try-server-hook** [comment]
[lightsofapollo James Lal (lightsofapollo)](https://github.com/lightsofapollo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=79e324abf9be)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=75d7ad099f4b8367ca3009b11c6bd8efb14614ef

**Pull request merged**
