### PR TITLE
Bug 1182129 - this backs out the entire privacy panel R=etienne

### PR DESCRIPTION
**Pull request by dhuseby**
The time has come to back out the privacy panel.  The bits we're keeping will go back in after being refactored and added where it belongs.

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b170fdb627f4505db1b02629250956a3f32d5bfc

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f475278d5e3089fe7f01208a218716609f23760e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0adf39a585f210c0627701b96c9560902a15d6c5

**Comment by dhuseby** [comment]
rebased onto current master.

**Pull request closed without merging**
