### PR TITLE
Bug 1196185 - Fix dialog does not show after dragging caret

### PR DESCRIPTION
**Pull request by aethanyc**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=45763fd701207687b443a91b23d3311405dd4342

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cb1f4600365157be639f583fefcec6b229e52f11

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5ccfe0ebccfa698acba0245a0d91fa3a7727ceec

**Comment by aethanyc** [comment]
Rebased my patches.

**Pull request merged**
