### PR TITLE
Bug 1076777 - Implement Application Manager menu with default launch app selection

### PR DESCRIPTION
**Pull request by fcampo**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[fcampo Fernando Campo (fcampo)](https://github.com/fcampo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f43b9ef108d4)

**Comment by try-server-hook** [comment]
[fcampo Fernando Campo (fcampo)](https://github.com/fcampo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c7e6b4592493)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=04354c121aed5a221afcedb1fbed408ac565a028

**Comment by fcampo** [comment]
<cleaning old stuff>

**Pull request closed without merging**
