### PR TITLE
Bug 1150953 - Wrap contact phone numbers in <bdi> tags on the Callscreen. r=thills

### PR DESCRIPTION
**Pull request by DouglasSherk**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f9f4a0a902b2747d6720e8c27f951e03af8221bc

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ba178505e6ca89fd059075f6872cce22c768c34d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=fdb36120483bc04fa56728cc97d61a3688b4b8bf

**Comment by autolander** [comment]
The pull request could not be integrated in as it contained a commit which was missing a bug number. Please ensure all commits contain bug numbers, and are in the format of: Bug [number] - [description]

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cf1f3f811e66fe25f24663189c2700b405abc091

**Pull request merged**
