### PR TITLE
Bug 1149886 - using <bdi> to replace <span> at Music app results in unable to locate <span.list-song-index> error. r=jlorenzo

### PR DESCRIPTION
**Pull request by HermesCheng**
a simple fix for gaia-ui-test v2.2.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2fbe3530158d4015e2c2d23f010c0b43495c5e1c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2fbe3530158d4015e2c2d23f010c0b43495c5e1c

**Comment by HermesCheng** [comment]
Treeherder try for v2.2 seems be green now, so reopen this PR

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2fbe3530158d4015e2c2d23f010c0b43495c5e1c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=64077afa1030b808b7005968ebc3cc8f74864848

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=64077afa1030b808b7005968ebc3cc8f74864848

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=64077afa1030b808b7005968ebc3cc8f74864848

**Pull request closed without merging**
