### PR TITLE
Bug 1163374 - Add localization for AccessFu MathML support.

### PR DESCRIPTION
**Pull request by fred-wang**
This is work in progress for https://bugzilla.mozilla.org/show_bug.cgi?id=1163374

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9e221c3ce9e2cf77aa125e78dfbbc1ae18d98dc5

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6cd79f3a4f80fd2183d7edae1f7fac66e7483988

**Comment by fred-wang** [comment]
@yzen @timdream is there additional procedure to ask this branch to be merged or is the review+ in bug 1163374 enough?

**Pull request merged**
