### PR TITLE
Bug 1224183 - history and bookmarks DataAdapter refactor, r=ferjm

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7031570205137ec4cdd991fa382e8e74bbea94ee

**Comment by michielbdejong** [comment]
Even after this refactor, the HistoryHelper and the BookmarksHelper still use very similar for the asyncStorage getters and setter. But they are used from within code that accesses the DataStore, and for history, some of that code now lives in the shared places_model.js, so no further refactor is possible at this moment.

We can create a follow-up bug to slim down the two helpers further, once https://bugzilla.mozilla.org/show_bug.cgi?id=1221226 is merged (but that's currently blocked, so might take a while).

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cc8bfdb61c7a124afdc6e6f6fede2f698ed49946

**Comment by michielbdejong** [comment]
Cleaning up PRs that are > 1 year old.

**Pull request closed without merging**
