### PR TITLE
Bug 1183726 - [Bugzilla Lite] Testing Dashboard Navigation(Assigned,Flagged,Filed) in Bugzilla Lite

### PR DESCRIPTION
**Pull request by mermi**
Need review, I have problem, it seems like he didn't find the css class for Assigned, Flagged and Filed

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=171b3a3d20e961f0b80e4f8170e6ae8d5e7bdb00

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9f8c1d20fec486c281fc7ea68f90ef3f400ae932

**Comment by mermi** [comment]
now the script let us to tap on the flagged bugs but don't let us to tap on filed bugs, I am searching if he can't find the element or there are another problem

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=07158ea789167239c28d4c3a374fa3bd066ee1ef

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=35bf72ce7a9e3c9c57f16ecc4b43e2e2ffbf792d

**Pull request closed without merging**
