### PR TITLE
bug 1222215 - Stop using per-file retry scheme. r=mhenretty

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=57e09e8ae423043c9a4f7bd1f3e5b494bb7db765

**Comment by mikehenrty** [comment]
Closing, this was just an experimental push.

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=57e09e8ae423043c9a4f7bd1f3e5b494bb7db765

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=57e09e8ae423043c9a4f7bd1f3e5b494bb7db765

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request closed without merging**
