### PR TITLE
Bug 1157609 - If user taps enter key in add contact page, device will…

### PR DESCRIPTION
**Pull request by rclaveau-tech**
… add phone field automatically. Depends on Bug 809452 R=francisco

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4659ae24d79e8ed5f24ea6c6cc21fca7926df67e

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#tmy63L7GRai8BEDvExS_5Q

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#ky27oWNKQQKQABQxRUwNZA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#EJ5nEx2zSTKOS9oAXWrHog

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
