### PR TITLE
Bug 1145551 - [Flame][Contacts]Device can't sent extension via sim2. r=d...

### PR DESCRIPTION
**Pull request by ferjm**
...rs

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b5ce32f33edc3d582f3ffec32ad2b092da5e204e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ada3ae7229f4a881abbb9bb3cd4b4ef0cd873678

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#wf143K9CRRi-Yly0V0GOZg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ada3ae7229f4a881abbb9bb3cd4b4ef0cd873678

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=97a767c55eec82a1f6dd8712ded0554b3ea1720b

**Pull request merged**
