### PR TITLE
Bug 1254079 - Load the rocketbar module only when making a phone build

### PR DESCRIPTION
**Pull request by albertopq**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0525fdd2dbbaa2c849ef596b44ad8d23dc129976

**Comment by ehabab** [comment]
جميل

**Comment by ehabab** [comment]
جميل

**Comment by ehabab** [comment]
جميل

**Comment by ehabab** [comment]
جميل

**Pull request closed without merging**
