### PR TITLE
appmodaldialog integration test - try run on ci 2

### PR DESCRIPTION
**Pull request by shamenchens**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1bb6177b489e5e2252e8e74a3dc4d20b04582551

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=211deec38422e0eb8b6e6da385b2ae9c714c56da

**Pull request closed without merging**
