### PR TITLE
Add logging and error to retry script for case when marionette-mocha output is missing a=test-only

### PR DESCRIPTION
**Pull request by lambdabaa**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[gaye Gareth Aye (gaye)](https://github.com/gaye) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=16a79d64cbdc)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[gaye Gareth Aye (gaye)](https://github.com/gaye) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=13295c930708)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[gaye Gareth Aye (gaye)](https://github.com/gaye) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=85d41b01e9c5)

**Pull request merged**
