### PR TITLE
Bug 1175835 - [Contacts][NGA] Extract 'sendEmailOrPick' from Contacts.js to Contacts_buttons.js

### PR DESCRIPTION
**Pull request by jpruden92**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=00725e79ae262912675c33dde1095294d84d40af

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2cae76c3d9b5a22ede31f0332ac508d14b939572

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=37f370b15fb7b2b84020d470da11e2b2d7d5bf0e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6c07dcde0465d189954064ba297f07e82a6dd683

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b3486e3b12ab66f0619026a25edcb17b44f75a47

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dd1648bfe578de749a89426746676f2dc2b71837

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dd1648bfe578de749a89426746676f2dc2b71837

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dd1648bfe578de749a89426746676f2dc2b71837

**Pull request merged**
