### PR TITLE
Bug 1123183 - [Stingray] Receiver app for video sharing

### PR DESCRIPTION
**Pull request by huchengtw-moz**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[huchengtw-moz John Hu (huchengtw-moz)](https://github.com/huchengtw-moz) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=36d849edb49b)

**Comment by try-server-hook** [comment]
[huchengtw-moz John Hu (huchengtw-moz)](https://github.com/huchengtw-moz) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2ee786720037)

**Comment by dwi2** [comment]
Do we need to include `build/build.js` ? Because I saw there are some `tv_shared` module in index.html

**Comment by huchengtw-moz** [comment]
Yes, you are correct.

**Comment by try-server-hook** [comment]
[huchengtw-moz John Hu (huchengtw-moz)](https://github.com/huchengtw-moz) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=836ea474dfa3)

**Pull request merged**
