### PR TITLE
Bug 1123672 - Investigate failure in test_IMAP_email_notification.py

### PR DESCRIPTION
**Pull request by viorelaioia-zz**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0ebf2937b4b3)

**Comment by viorelaioia** [comment]
http://jenkins1.qa.scl3.mozilla.com/job/flame-kk.ui.adhoc/607/console

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ad1f5092cd5d)

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b5ff9a4f3f1c)

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c08960e55654)

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c88ee3039526)

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d69450db0bb4)

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8b9f2ca9170b)

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2c183d5c8426)

**Comment by viorelaioia** [comment]
http://jenkins1.qa.scl3.mozilla.com/view/UI/job/flame-kk.ui.adhoc/616/console

**Pull request merged**
