### PR TITLE
[Clock] Bug 1124965 - Double-tapping "Save" on the Alarm Edit screen results in undeletable alarms. +autoland

### PR DESCRIPTION
**Pull request by mcav**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[mcav Marcus Cavanaugh (mcav)](https://github.com/mcav) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8feef647c5c7)

**Comment by try-server-hook** [comment]
[mcav Marcus Cavanaugh (mcav)](https://github.com/mcav) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=468e56a26e77)

**Comment by autolander** [comment]
The pull request could not be integrated in as it contained a commit which was missing a bug number. Please ensure all commits contain bug numbers, and are in the format of: Bug [number] - [description]

**Pull request merged**
