### PR TITLE
Bug 1142526 - Treat the innerHTML attribute as the string's value

### PR DESCRIPTION
**Pull request by stasm**
https://bugzilla.mozilla.org/show_bug.cgi?id=1142526

### CODE REVIEW

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=a5177b44c0bd)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=776c8be869de)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e83e8deac7ee)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ef823be67c18)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d89e1d666dcc)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=88c8eae07ddb)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e160b3d1e09ae434df17e40d4f10c39182c4a3a4

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e92d61383d12cf39dc3237d15b6a3d8d531bed4c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ab5b372e9e0c6f88953b9b2b34c3b08247c3d943

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2dd503651c08166bc0a6b5b917ff0571fde87ae6

**Pull request merged**
