### PR TITLE
Bug 1174297 - Introduce npm scripts

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e47dac30b6e3d6f1da2a61b308ec645291d128cd

**Comment by gaye** [comment]
Do you want to change the Makefile to call npm marionette instead of ./node_modules/.bin/mocha? Also can you confirm npm run refresh works for you?

**Comment by gaye** [comment]
@Eli ^^

**Comment by eliperelman** [comment]
Here is my output of `npm run refresh`:

```sh
➜  gaia (bug-1174297) ✔ npm run refresh

> gaia@0.0.3 refresh /Users/eli/code/gaia
> npmr install
```

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b2cd5a260d738693dce13f300d7468c2ca3f413c

**Pull request merged**
