### PR TITLE
Bug 1206474 - Changed SIM related strings

### PR DESCRIPTION
**Pull request by vinay-y**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9ccaf36591897992f12444676b4dde52e966384f

**Comment by vinay-y** [comment]
Commit message has wrong bug number. Title has the correct one.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7192ca326eaefda410179ba0bc301b89d0ac66d3

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c89df0b430a1bcecc69d3e6c832b5a65115655f9

**Pull request merged**
