### PR TITLE
Bug 1232281 -  added Gij test: pressing home button will do nothing effects LockScreen

### PR DESCRIPTION
**Pull request by snowmantw**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2486d381efccc657ce4f43ddaa1a62b549f65bd3

**Comment by timdream** [comment]
Please make commit message more descriptive!!!

**Comment by snowmantw** [comment]
To describe test is too verbosed; to add test name

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2486d381efccc657ce4f43ddaa1a62b549f65bd3

**Comment by snowmantw** [comment]
@timdream: To describe test steps is too verbosed; to describe the test name is duplicating the bug title which has been advised not to do that, but that's the only descriptive part of this patch.

**Comment by timdream** [comment]
> @timdream: To describe test steps is too verbosed; to describe the test name is duplicating the bug title which has been advised not to do that, but that's the only descriptive part of this patch.

I don't see the bug being titled as the test name ("Pressing home button will do nothing effects LockScreen"), so the correct commit message should be "Bug 1232281 - Gij test on pressing home button will do nothing effects LockScreen".

**Comment by snowmantw** [comment]
I meant test file name indicates Gip file name, but test name is a good idea, so I will change that before the landing.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=521a3d3c45a2a68313c4b22379c9423b5bf47a94

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b9879fa58a912e97c31cde41f0570cad45507078

**Pull request merged**
