### PR TITLE
Bug 997547 - [MMS]Text to email from Contact details

### PR DESCRIPTION
**Pull request by delapuente**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=bba98b6e0451)

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=89eca3bd70fd)

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7d8548872957)

**Comment by lodr** [comment]
This bug if cursed! Re-open again!

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b621b069562b)

**Comment by lodr** [comment]
Please, be green this time...

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0dcc84174baa)

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f20bece312f7)

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8e444eebf038)

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=72636355f808)

**Comment by try-server-hook** [comment]
[lodr Salvador de la Puente González (lodr)](https://github.com/lodr) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7caf34fbce29)

**Pull request merged**
