### PR TITLE
Bug 1214193 - Deal with unknown incoming tombstones

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=30a3a6a358c2476467ee0d1ba81177a03e884874

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=826a98a5c2370963dd509ef8878ae70cb71701f2

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=353469496ee574689a559717c00c4801ab912081

**Comment by michielbdejong** [comment]
See last commit.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=26b60d53e2b4d5f02552016e19b61cbb6f95c3fc

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f607ec949db9660fd79e063594c54c52a833e3c3

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d2b8db686519194ab754370927304fbf22ea0997

**Comment by michielbdejong** [comment]
Changed the console warning from 'No DataStore ID corresponded to FxSyncID' to 'Ignoring incoming tombstone for unknown FxSyncID', which is a bit more descriptive.

I was confused when I saw the warning message in practice, even though I worked on the bug myself. :)

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=57add6d1795e09b40486098d57f6f94a713d6cf5

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a4bbbe4f85021e55af07ccfa60446ff2fbafca3c

**Pull request merged**
