### PR TITLE
Bug 1102972 - ensure rebuilding app removed from profile folder.

### PR DESCRIPTION
**Pull request by ochameau**
https://bugzilla.mozilla.org/show_bug.cgi?id=1102972

### CODE REVIEW

**Comment by try-server-hook** [comment]
[ochameau null (ochameau)](https://github.com/ochameau) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=9d713c9f452b)

**Comment by ochameau** [comment]
Rebased.
I've let the JSON.parse in order to keep the custom "uuid.json in GAIA_DISTRIBUTION_DIR found." log msg.

**Comment by try-server-hook** [comment]
[ochameau null (ochameau)](https://github.com/ochameau) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d3dfa04a6f6d)

**Comment by RickyChien** [comment]
@ochameau hey, I saw there are 3 Gbu failures even though it's green.

**Pull request merged**
