### PR TITLE
Bug 1172356 - [Settings] Convert accessibility switches to use gaia-switch

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1172356

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2033e793cb1041307bd6239396cfa77a6a7119a0

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=39f2b36cd183c2a529cc31506d66ea626aa5b653

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4f881cad746dbc0c0cfcb393c4ba89072da9a186

**Comment by KevinGrandon** [comment]
Try run: https://treeherder.mozilla.org/#/jobs?repo=try&revision=10b718395260

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=37876410e1bb7ed930ed995765fa5da48b53d8d7

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=45ebd4e0ed71e76df0f6b05a1bd79a1a9962f034

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cc0705ade06329ccb0163cc29427a2781227fd80

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c26449c66526ac9465fe941b0d1132baef112974

**Pull request closed without merging**
