### PR TITLE
Bug 1142060 - Fix foriIntermittent test_homescreen_delete_app.py

### PR DESCRIPTION
**Pull request by mwargers**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=84a014d0626c6f872a499b449a5f180d84ee6264

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=84a014d0626c6f872a499b449a5f180d84ee6264

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=88d91ee756a1aaf78afe76b974e9873bf3e197d6

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=665710afdc75e4b821693b7a49dc8339a6c2b62b

**Pull request merged**
