### PR TITLE
Bug 1136549 - Replace evt.device.name with evt.deviceName when accessing BluetoothPairingEvent, r=ian

### PR DESCRIPTION
**Pull request by yrliou**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[yrliou Jocelyn Liu (yrliou)](https://github.com/yrliou) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=df778edfd6cb)

**Comment by ian-liu** [comment]
The format name of the pull request is needed to revise.
Ex: Bug 1136549 - Replace evt.device.name with evt.deviceName when accessing BluetoothPairingEvent, r=ian

**Comment by try-server-hook** [comment]
[yrliou Jocelyn Liu (yrliou)](https://github.com/yrliou) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=171297fde6da)

**Comment by ian-liu** [comment]
There is no reason to make unit failed with commit message updated. Let's merge the pull request with above unit test result.

**Pull request merged**
