### PR TITLE
Bug 1236863 - Bring sync app in v2.5 up to date with master, r=ferjm

### PR DESCRIPTION
**Pull request by michielbdejong**
I copied the following folders from master:
- `apps/sync`
- `shared/js/sync`
- `apps/sharedtest/test/unit/sync`

Any paths I forgot?

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=482b8acef367cb768d266700d63254c8b0e29c49

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=65fdc86c024cef6cde696a0542008ebe39678987

**Comment by michielbdejong** [comment]
Ah, I had forgotten `build/config/common-settings.json`, added.

**Comment by michielbdejong** [comment]
Found a problem running the tests from `apps/sharedtest/test/unit/sync`, will fix.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d0623c9dab29f083af770965a50312290957aafc

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1b2a07b3d660bdcf5e61fb363691444a0e41d36b

**Comment by michielbdejong** [comment]
Script used for generating the first commit ("Part 1") of this branch:
````bash

git checkout b2g-master
git pull
cp -r apps/sync ./apps-sync
cp -r shared/js/sync shared-js-sync
cp -r apps/sharedtest/test/unit/sync apps-sharedtest-test-unit-sync
cp build/config/phone/device.mk build-config-phone-device.mk
git checkout v2.5
git pull
git branch 1236863-sync-app-from-master
git checkout 1236863-sync-app-from-master
rm -r apps/sync
mv apps-sync apps/sync
rm -r shared/js/sync
mv shared-js-sync shared/js/sync
mv apps-sharedtest-test-unit-sync apps/sharedtest/test/unit/sync
mv build-config-phone-device.mk build/config/phone/device.mk

# edit build/config/common-settings.json
#   "sync.collections.history.enabled": true,
#   "sync.collections.passwords.enabled": false,
#   "sync.collections.bookmarks.enabled": false,
#   "sync.collections.history.readonly": true,
#   "sync.collections.passwords.readonly": true,
#   "sync.collections.bookmarks.readonly": true,
#   "sync.collections.history.limit": 50,
#   "sync.collections.passwords.limit": 2000,
#   "sync.collections.bookmarks.limit": 2000,

# edit build/config/tv/settings.json
#   "sync.collections.history.limit": 500,

# edit apps/sharedtest/test/unit/.jshintrc
#   "expect",

# edit .jshintignore
#    apps/sync/js/ext/kinto.min.js -> shared/js/sync/ext/kinto.min.js

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0759bf96fe0f5db8826021e4f32f34f0d498ace0

**Pull request merged**
