### PR TITLE
Bug 994357 - Use DOM overlays for safely setting node content

### PR DESCRIPTION
**Pull request by stasm**
https://bugzilla.mozilla.org/show_bug.cgi?id=994357

### CODE REVIEW

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=6874e074d2d0)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7373e02e86c9)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=699045a009d8)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f2c0ce454ea3)

**Comment by try-server-hook** [comment]
[stasm Staś Małolepszy (stasm)](https://github.com/stasm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=46a278bbc18f)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c5df5a0b281b5c532e5d59cd762625f31a12cc35

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1b334d76c0754b6a3a3dd94a4a85ed7b510bd843

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a8bafb01c9f0e07f4dfb80b1c9d8b960574cc796

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#FwsCsVZqTayT2HWe-XAsMQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7716352332da24d8af54c36993e569582d908f9b

**Pull request merged**
