### PR TITLE
Bug 1162040 - updating to latest gaia-icons and updating shared style…

### PR DESCRIPTION
**Pull request by yzen**
…s that include gaia-icons.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0e691a969ac388e9703c0c155edd39a0ecda015d

**Comment by wilsonpage** [comment]
Did you use Bower to update this?

```bash
$ cd shared && bower update gaia-icons
```

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=44c8899ca869099257d8d93bee6ba367c6692e8d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=10f86e0b40d9f77ebfaf1f0f6718b2a6155cbaa1

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c17a31df325eadf0d1e9a6145f4bb6b3e2ba1ec1

**Pull request merged**
