### PR TITLE
Bug 1140329 - [Contacts]The contact's Birthday is not same as that in PC...

### PR DESCRIPTION
**Pull request by ferjm**
... if it is a contact imported from oultlook account. r=francisco

### CODE REVIEW

**Comment by try-server-hook** [comment]
[ferjm Fernando Jiménez Moreno (ferjm)](https://github.com/ferjm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=966eda8c5aff)

**Comment by try-server-hook** [comment]
[ferjm Fernando Jiménez Moreno (ferjm)](https://github.com/ferjm) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b74e20487b8f)

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#DtBeDwD5TAe-83Qw-_oNrQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#QYiES6IUTkSdn_UOSExGWg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#jmKXLdVARn2KIFZ1W9JNYQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
