### PR TITLE
Test bug1070823 panel support v2 api

### PR DESCRIPTION
**Pull request by ian-liu**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[ian-liu Ian Liu (ian-liu)](https://github.com/ian-liu) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7e8001bad062)

**Comment by try-server-hook** [comment]
[ian-liu Ian Liu (ian-liu)](https://github.com/ian-liu) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8acca20cf1df)

**Comment by try-server-hook** [comment]
[ian-liu Ian Liu (ian-liu)](https://github.com/ian-liu) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2dea49abba49)

**Comment by try-server-hook** [comment]
[ian-liu Ian Liu (ian-liu)](https://github.com/ian-liu) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c28e4b48f9e6)

**Comment by ian-liu** [comment]
Since we found out the failed reason of Gij/Gip, we can close the pr here.

**Pull request closed without merging**
