### PR TITLE
add voice search icon to rocketbar placeholder in vertical homescreen.

### PR DESCRIPTION
**Pull request by nullaus**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0a033b2586f3)

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=11aabd5d42ff)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=38a650795d13)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f4ab0e099236)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e833c4d25c1a)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=a9afccd008ba)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d20f175218ee)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=23c75ec0770d)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=28269873c96b)

**Pull request closed without merging**
