### PR TITLE
Bug 1147786 - Fix being able to show delete-app dialog twice. r=kgrandon

### PR DESCRIPTION
**Pull request by Cwiiis**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a3fc66a4d84779536da7a682e3562868374a9a1f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6b6c256062fe1d9a876b932d39c7e7ed1ca4797f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ae9472c09c0585f5428c3f6c87171de033bc6554

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#M31lXx7qSBKs_P_LOJugAA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
