### PR TITLE
Bug 1172328 – change "foward" to "forward"

### PR DESCRIPTION
**Pull request by pollti**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=21344b2fd8e29375cedf3e9280886aa6f841603f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=296695ece595331cce01b4699f8c9c50ca6d643a

**Comment by timdream** [comment]
Close and reopen to rerun tests.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=296695ece595331cce01b4699f8c9c50ca6d643a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=296695ece595331cce01b4699f8c9c50ca6d643a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=387556cba4a98ab6f67f84f3731ffa3f8e77024c

**Pull request merged**
