### PR TITLE
Bug 1202571 fix integration test

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0d251400c0543742ddfe59c3763c318cc9e2bdf0

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8b2cc71a16063eaee9e36bf546bb8d8cb97a7118

**Comment by mikehenrty** [comment]
Closing this in favor of #32503

**Pull request closed without merging**
