### PR TITLE
Bug 1158043 - Fix ellipsis in the song title.

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e0e1b06095accb4dc727fa18798c80d9556544c2

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#4hen9ro_Sv-1becrrW3jcg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#jUcWw412QcWdAGLNT16RSA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#7Qsvg5RHTLmdPCKHdUndTQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#JEt9U84ZTpmODsyBLj4IYw

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7ff8e7796dacdfb875f6cdff7d24bd687c86711d

**Pull request merged**
