### PR TITLE
Bug 1160883 - Add Frisian (fy or fy-NL) wordlist/dictionary.

### PR DESCRIPTION
**Pull request by RudyLu**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ec13d8177f7f5159f0411b9c8be7eb825c398de4

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#ztZnQQTDTUStQsfEvWmf7g

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3ac5db816d0b8260869c5baaa6a693f744d13856

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=480498e9ce0a8044446d1506ba7df9d0100aadd7

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a5d9b4cfab83588805668570c58b057cc46f3808

**Pull request merged**
