### PR TITLE
Bug 1156607 - Fix remaining FTU jshint issues

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1156607

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2c104db484965d0461afb58b4f0a2c1bb877400e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=70188ebf16e3b399488b143dc4340d87f65ebb5f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4034fd9d135803ddafbb92e6ab7e87a133857695

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d29fd095924c3cc7de74aa9c1d27ebb292645276

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#iEPe4xckRMakZU3hbVoO7g

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#iqY0O9kaSAiSxiX39Y46Gg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#jgDNozIFQcesjhVSv7Zvkg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=56f5765b725259a658010425542188cfa085610b

**Pull request merged**
