### PR TITLE
Bug 1202126 - alternative keyboard layout neo has english auto correc…

### PR DESCRIPTION
**Pull request by MichaelKohler**
…tion & word suggestion, but it should be german

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ebd79311654717a88fdb01ddc5d642c14e5c05d9

**Comment by MichaelKohler** [comment]
oops, there is a failing test, let me have a look at it tomorrow

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6615721cb7546d6a04850db03ee59efa80480400

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9089ec778bae328fff15e494402dc61dd7e8408d

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=55ec88430061ebc39a228cfacce578f0cf07d279

**Pull request merged**
