### PR TITLE
Bug 1243539 - A web app to test metadata parsing.

### PR DESCRIPTION
**Pull request by hfiguiere**
Currently only loading ogg....

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9c45b5afb56b24c06175fb5d2266f285a1ab489f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8a2571b3a062d2f378e0b0eef3f6cbbbc28c7d1b

**Comment by hfiguiere** [comment]
Now supporting all the format we support.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=98ff4872de080cc985cfdeb76867eefaf720eb09

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=55e599866b0cec4f1e38f656ca61e44b808c1401

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=706bde0564b2431634f26a31a8add4c00ed8f69e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e087285897af8c940b731f955a441da46193a543

**Pull request merged**
