### PR TITLE
Bug 1165493 - marionette-apps@0.3.13

### PR DESCRIPTION
**Pull request by lambdabaa**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d2f276b4dbb5f6ca2e9f775dccc3f032f636afd4

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b0f2045c520e981273b346e0e4d7e40906bef83c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=86d4528a0244a8e916fad8daec6c256869589b9a

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ae5261211e25d14fd01f2c177a0dd4a46b603947

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e77d463778636ef882e13cebd4788717596d82f9

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1b7fdd3251a40b20c3a90ba1513c8deb20cc3baf

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=55abe20c7a98995e77485398d74db0a93ab299b6

**Pull request merged**
