### PR TITLE
Bug 1141792 - Use npm-cache taskcluster docker worker image to create no...

### PR DESCRIPTION
**Pull request by nullaus**
...de module cache. Use cache in gaia docker worker image. r=lightsofapollo

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1be7d7387575b6149ffcb9deb2a0aefeb05c9371

**Comment by msujaws** [comment]
This was filed with the wrong bug number.

**Comment by nullaus** [comment]
Corrected bug number in pull request title.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8409a31ab950ebdd4a5ca156677e1e81a6d0d202

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0eb1af5c766aeca7c013c31608443a4b78cf48cc

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6dff85339e2e6f35f7ccaea16abc18865f9db3fa

**Pull request closed without merging**
