### PR TITLE
Bug 1178290 - [Gallery] Use MediaFrame.maxImageDecodeSize to calculate output size in pick flow r=djf

### PR DESCRIPTION
**Pull request by punamdahiya**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7c6aae45d17b89dec3cb08c20f4001e8839e8c9d

**Comment by hfiguiere** [comment]
Also GU19 in the gaia-try run is orange. And given the change I believe it is caused by it.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=824e6eff9b1331a3394bb87d160b34211c89886c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d93ff3e5001e35ed7929b0073d1da55435a85870

**Pull request merged**
