### PR TITLE
Bug 1216050 - remove fack tv channel info, r=rexboy

### PR DESCRIPTION
**Pull request by evelynhung**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=fef7c0bf68013c25406988d87fb0531f8a184b8e

**Comment by rexboy7** [comment]
We got another one included in `tv-epg/test/marionette/tv_epg_test.js`. Let's remove it and land after confirming GijTV is still correct.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e21b4fa39903a214e369899511cb722ac9e1573e

**Comment by evelynhung** [comment]
I guess we still need it for integration test, so I moved the file to shared test folder.

**Pull request merged**
