### PR TITLE
Bug 1074117 - Use expected conditions and optimise element lookups in settings app object

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=823974def487)

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e132c5cc9e8d)

**Comment by bebef1987** [comment]
http://jenkins1.qa.scl3.mozilla.com/job/flame-kk.ui.adhoc/656/console

**Comment by davehunt** [comment]
Merged in https://github.com/mozilla-b2g/gaia/commit/a0529167d625c8a99d58ff249b12b98bd2aff973

**Pull request closed without merging**
