### PR TITLE
Bug 1139238 - disable buletooth/wifi button click handler when 'airplaneMode' is switching. r=arthur.chen.

### PR DESCRIPTION
**Pull request by mpizza**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[mpizza GaryChen, PYChen (mpizza)](https://github.com/mpizza) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0b9dae604683)

**Comment by try-server-hook** [comment]
[mpizza GaryChen, PYChen (mpizza)](https://github.com/mpizza) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d54f2899c742)

**Comment by try-server-hook** [comment]
[mpizza GaryChen, PYChen (mpizza)](https://github.com/mpizza) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b0d2d89210fd)

**Comment by try-server-hook** [comment]
[mpizza GaryChen, PYChen (mpizza)](https://github.com/mpizza) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=6c7fd610861b)

**Pull request merged**
