### PR TITLE
Bug 1219682 - added Gij test: create a notification after locking the device, and to see if it shows

### PR DESCRIPTION
**Pull request by snowmantw**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=560acdfbeb9fc90578ddf69b56bfd3f9d1de09e5

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=894206b2236cac55023a2e63b15f185428250252

**Comment by timdream** [comment]
Please update the commit message!

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=873cc517274fe3c188402318cb212fba9c55f5b6

**Pull request merged**
