### PR TITLE
Bug 1229321 - add shrink ui test

### PR DESCRIPTION
**Pull request by nhirata**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8866027479ce60f9c685f10522a814c72bd294f1

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e5b04bdd7febf6611ea38641be1f741cac319212

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=46b6d6da53c4e06052849840df73a769eeab9e1e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4569cb4d9094e184f7fba51418ca40da6c47216a

**Comment by nhirata** [comment]
Not to be checked in.

**Pull request closed without merging**
