### PR TITLE
Bug 1131356 - update tests for marionette-driver becoming available

### PR DESCRIPTION
**Pull request by AutomatedTester**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[AutomatedTester David Burns (AutomatedTester)](https://github.com/AutomatedTester) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8078cf8d236c)

**Comment by bebef1987** [comment]
We are missing one import:

https://github.com/mozilla-b2g/gaia/blob/master/tests/python/gaia-ui-tests/gaiatest/tests/functional/cost_control/test_cost_control_data_alert_mobile.py#L9-9

**Comment by try-server-hook** [comment]
[AutomatedTester David Burns (AutomatedTester)](https://github.com/AutomatedTester) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e5a1216db0ad)

**Pull request merged**
