### PR TITLE
Bug 1154695 - Remove import of InvalidResponseException

### PR DESCRIPTION
**Pull request by andreastt**
r=davehunt

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c5e9dbdbc7c12e13b3327e093f2db7f1f75c653e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e143b458d9716a20e1caee2fc08a0ddfa285e8b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e143b458d9716a20e1caee2fc08a0ddfa285e8b

**Pull request merged**
