### PR TITLE
Bug 1157615 - 2 fingers taps should never trigger edge gestures. r=alive

### PR DESCRIPTION
**Pull request by etiennesegonzac**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=84f9d36fb130eb7ba737605e539abd527c37b9ac

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=908ee66a87701b2653421e80a61d053abbc35902

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#CsaBdfNyRAufULYJr7z9Bg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d56426a25674ff6736ee6354f89df40377da61ea

**Pull request merged**
