### PR TITLE
Bug 1040177 - Lazy load activities.js when a web activity is called r=francisco

### PR DESCRIPTION
**Pull request by Aspirar**
The script tag loading activities.js has been removed from index.html. The file has instead been lazy loaded in the function initContacts() in contacts.js.

### CODE REVIEW

**Comment by try-server-hook** [comment]
[Aspirar Lakshya Gupta (Aspirar)](https://github.com/Aspirar) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=49d463b11851)

**Comment by try-server-hook** [comment]
[arcturus Francisco Jordano (arcturus)](https://github.com/arcturus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=afb4c0f9d493)

**Comment by try-server-hook** [comment]
[Aspirar Lakshya Gupta (Aspirar)](https://github.com/Aspirar) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=67377f5b619a)

**Comment by arcturus** [comment]
Closing and reopening bug, lots of busted test, that doesn't have to do with this patch

**Comment by try-server-hook** [comment]
[arcturus Francisco Jordano (arcturus)](https://github.com/arcturus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=1fd66afa99a4)

**Comment by try-server-hook** [comment]
[Aspirar Lakshya Gupta (Aspirar)](https://github.com/Aspirar) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=426a61627561)

**Comment by try-server-hook** [comment]
[Aspirar Lakshya Gupta (Aspirar)](https://github.com/Aspirar) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=cb97fe163710)

**Comment by arcturus** [comment]
Trying again to open an close the PR, seems we had a problem with threeherder

**Comment by try-server-hook** [comment]
[arcturus Francisco Jordano (arcturus)](https://github.com/arcturus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=04acce85268e)

**Comment by try-server-hook** [comment]
[Aspirar Lakshya Gupta (Aspirar)](https://github.com/Aspirar) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=beea7ab9849f)

**Pull request closed without merging**
