### PR TITLE
Bug 1282723 - Update working web apps & add WIP apps in gaia page

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=49b9836f3a29a189f78b9a1f857715e86f3c698f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d957384460c9f51f740de0d45811413dc24b0f0a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d957384460c9f51f740de0d45811413dc24b0f0a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d957384460c9f51f740de0d45811413dc24b0f0a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=71b9677b8627b0729e6348c39c8e1d197b37c7d1

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e6c09b96fdff4a3efc6c67d92ddb1fec97bb7c6e

**Comment by kskarthik** [comment]
@benfrancis need your review here

**Pull request closed without merging**
