### PR TITLE
Bug 1145955 - Add Greek characters to prediction engine's variant form t...

### PR DESCRIPTION
**Pull request by past**
...able. r=rlu

### CODE REVIEW

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#l7hW9KxqSaKwVbd_Alof4w

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=62c1803970024b133aa8ab19d154d844576a55fa

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#F5-riq1rQZGWppk22Y6j2w

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=62c1803970024b133aa8ab19d154d844576a55fa

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#iL1yL9Z_TWCxJZ0HHvOjpA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#7VLDNrR0RVS_Q5rqVcuGpg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=41f6ba1251d10aecd052592563746015fdde03ff

**Comment by autolander** [comment]
The pull request could not be integrated in as it contained a commit which was missing a bug number. Please ensure all commits contain bug numbers, and are in the format of: Bug [number] - [description]

**Pull request closed without merging**
