### PR TITLE
Bug 1157163 - Fix how camera may be reopened too early when using the preview gallery. r=justindarc

### PR DESCRIPTION
**Pull request by aosmond**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bbce14d1a65483296808daa9c28d5b026f6f9743

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete. You may need to rebase your branch against the target branch.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ee630b86a6d6505273b4251bff49352aebc5761f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=324e312cf875c824ece015d2d85713b3e512cfe6

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete. You may need to rebase your branch against the target branch.

**Pull request merged**
