### PR TITLE
Bug 1146208 - Add performance measurement mark prior to entering wifi pa...

### PR DESCRIPTION
**Pull request by elefant**
...nel.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cd9db54db8126e151441a23b06ea94bdd1a18060

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cd9db54db8126e151441a23b06ea94bdd1a18060

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d451798ecec693de0ea76788e57e870f2cc1df68

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#f3Odq5QgQiWbgaLAFEMgEg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5a14c45558fb2036401fbacf2d2da31536095ab0

**Pull request merged**
