### PR TITLE
Bug 1136122 - Separate host and device SMTP account details

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=752ce13d46a6)

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b03754b3f572)

**Comment by geoelectric** [comment]
Also LGTM

**Comment by davehunt** [comment]
Merged in https://github.com/mozilla-b2g/gaia/commit/4a5a2ce14f9c62adc72b43e60aa69ef0c93e8491

**Pull request closed without merging**
