### PR TITLE
Bug 1147173 - [music] Improve the initial-run experience for the music app

### PR DESCRIPTION
**Pull request by jimporter**
Reduced version of https://github.com/mozilla-b2g/gaia/pull/29114 with the last two commits stripped

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c590b7c12f138e9d87bf78a0cca24934cc4ff3e6

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#-0Hn05QxRwCrOqcSbJgBTA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c590b7c12f138e9d87bf78a0cca24934cc4ff3e6

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7b2e9a66d1eb2d10deee85adff7416484339d9c3

**Pull request merged**
