### PR TITLE
Bug 1151902 - test_dialer_find_contact.py: "IndexError: list index out of range"

### PR DESCRIPTION
**Pull request by gerrycfchang**
Uplift fix of 3.0 to 2.2. @mwargers r?

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7b878060b3d3926651b81d489bd6803b5237a7dc

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=54949a3102fc30e71888869ff7ffa61e1dc7d0bd

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7b878060b3d3926651b81d489bd6803b5237a7dc

**Comment by gerrycfchang** [comment]
Please ignore this pull request.

**Pull request closed without merging**
