### PR TITLE
Bug 1150573 - Fix javascript exceptions in test_play_3gp_video.py and mo...

### PR DESCRIPTION
**Pull request by mwargers**
...re

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c7fd36d5e101ab7598b5537f586cfe9fb9a72e57

**Comment by davehunt** [comment]
The new message is misleading as the comparison is of a count of video files. We can't assume there are none, we only know the expected value does not match the expected value.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ccc13f37b632140122d4dc7b8126dc2f8d589402

**Comment by mwargers** [comment]
Ok, I removed the whole message.

**Pull request merged**
