### PR TITLE
Bug 1117813 - Make PlivoUtil use a valid 'answer_url' with a valid Plivo...

### PR DESCRIPTION
**Pull request by JohanLorenzo**
... XML

### CODE REVIEW

**Comment by try-server-hook** [comment]
[JohanLorenzo Johan Lorenzo (JohanLorenzo)](https://github.com/JohanLorenzo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=cc80210cc9fa)

**Comment by try-server-hook** [comment]
[JohanLorenzo Johan Lorenzo (JohanLorenzo)](https://github.com/JohanLorenzo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=fbb9adb34a22)

**Comment by try-server-hook** [comment]
[JohanLorenzo Johan Lorenzo (JohanLorenzo)](https://github.com/JohanLorenzo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f0337cbf12dd)

**Comment by JohanLorenzo** [comment]
Mass closing PRs. Gaia is not a supported project anymore.

**Pull request closed without merging**
