### PR TITLE
Bug 1159457 part 1 - Rearrange homescreen for Spark apps. r=drs

### PR DESCRIPTION
**Pull request by tedders1**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9cbd936fdce2eda341490eab6b0218ebda7f2014

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d72965aad3adbb2e7d0fe2046e63df7cb40d618e

**Pull request closed without merging**
