### PR TITLE
Bug 1167654 - Ensure we don't return nextpaint promise if we don't resize

### PR DESCRIPTION
**Pull request by timdream**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d9b6e183d732f1abe5b2fa8d9641c76550e5ddb9

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#mhITi_DpSdGkv3XfzX8OnA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#YI3BxHonQJ--4QYq0KETyA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=20c0fcc12069486ed894505362c60c78b1582bdc

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#uQNT_cuKScS71Ye1DY8UHA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
