### PR TITLE
Bug 1256227 - Add last_modified property into Tabs sync record.

### PR DESCRIPTION
**Pull request by weilonge**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bb5fe2838527ed9c0784956b0822fd8f494dd232

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=24da206b5e69fa9b6545072a9c0894cec9b9c027

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=275468056e56b3d4d5785e17d23c4f68ef054518

**Comment by michielbdejong** [comment]
r+wc: please rename 'updateTab' to something more like `updateDeviceTabsList`, to indicate that you're updating the record which lists the currently open tabs of one synced device.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f6906d60d426adc545ad02129f4b92cdfc70daf0

**Pull request merged**
