### PR TITLE
Bug 1119024 - Use number instead of string r=eragonj, drs

### PR DESCRIPTION
**Pull request by crh0716**
https://bugzilla.mozilla.org/show_bug.cgi?id=1119024

### CODE REVIEW

**Comment by EragonJ** [comment]
https://github.com/mozilla-b2g/gaia/blob/master/apps/settings/js/panels/simcard_manager/simcard_manager.js#L97

This can be `===` after applying this patch

**Comment by EragonJ** [comment]
Good news : https://github.com/mozilla-b2g/gaia/blob/master/shared/js/sim_settings_helper.js#L81

We did force stored type to `Number` here. So it means that we can easily update all other places !!

**Comment by EragonJ** [comment]
https://github.com/mozilla-b2g/gaia/blob/master/apps/communications/dialer/js/dialer.js#L412

use `===`

**Comment by EragonJ** [comment]
https://github.com/mozilla-b2g/gaia/blob/master/apps/emergency-call/js/dialer.js#L18

use `===`

**Comment by EragonJ** [comment]
https://github.com/mozilla-b2g/gaia/blob/master/shared/js/multi_sim_action_button.js#L7

Change to `-1`

**Comment by try-server-hook** [comment]
[crh0716 Arthur Chen (crh0716)](https://github.com/crh0716) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c241f96b5813)

**Comment by try-server-hook** [comment]
[crh0716 Arthur Chen (crh0716)](https://github.com/crh0716) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4fd449f50517)

**Comment by try-server-hook** [comment]
[crh0716 Arthur Chen (crh0716)](https://github.com/crh0716) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7d52c574a99c)

**Pull request merged**
