### PR TITLE
Bug 1151618 - waiting for the initial card to be visible instead of hard...

### PR DESCRIPTION
**Pull request by yzen**
... assert.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=84ce3be5715aac7767ef8a67b9f38886d2c2af44

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4f9e39d40b0af7496e1d935356e727377e71dbf1

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#ZMuYhty-RiWW-mthcuAj1A

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#S9MTBqkFRIOJB9DneMZMiQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
