### PR TITLE
Bug 1226166 - [WiP] Move places model from system app to shared, r=da…

### PR DESCRIPTION
**Pull request by michielbdejong**
…leharvey

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ae4cd469149f4ee0646b04edba68512429fa2984

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1827bac5e64863b4d8d26a0962e2125b5e1c5229

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a41c5f05a6bef067cd1ea250b839c3ea3fd3eaaf

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9994ee7f395d3351c4cd6424356ceb70d387e2a5

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=97145ffcf9a6c97829ff90f3ab5cdc54e48a9a29

**Comment by michielbdejong** [comment]
Cleaning up PRs that are > 1 year old.

**Pull request closed without merging**
