### PR TITLE
Bug 1180624 - [Bugzilla Lite] Testing the Log in to Bugzilla Lite

### PR DESCRIPTION
**Pull request by mermi**
@JohanLorenzo Need review

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1c2c12ecb96e67936e05d44033addfe8cb2ebf6a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6c63b38065af939dcd8eedcc707f13d942143d7b

**Comment by mermi** [comment]
@JohanLorenzo I added the manifest file, please could you check it :)

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=99e1b00d1f57f629b3cc524e5a38da31ba023449

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6c36248711e0993a67311a274890424c852382d1

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=877d7000a4468be039ae063e227a7e7d1272d020

**Pull request merged**
