### PR TITLE
Bug 1173346 - Allow hiding the Developer HUD elements. r=vingtetun

### PR DESCRIPTION
**Pull request by jankeromnes**
Drive-by change: Don't show USS by default, making the HUD more discreet (only show critical problems when applicable).

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2c0dc292d8f698bc3a0e997f16805483fc3108b1

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=481b909b2b10eb0b98eb23d0692a4e723e21e627

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=84cebcbbe7aa7292bad2874e5c43f6a9077dc799

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=09e189da44ab8de5ad23b456014fae719f821cf3

**Pull request merged**
