### PR TITLE
Bug 1128053 +autoland

### PR DESCRIPTION
**Pull request by timdream**
Revert "Merge pull request #25305 from timdream/value-selector-focus"

This reverts commit 47faa4651f8feb11152ef475850cc9641fd5cbeb, reversing
changes made to 4c7e1e5f68ec57241d488568080732b318d652f5.

Conflicts:
    build/jshint/xfail.list

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[timdream Timothy Guan-tin Chien (timdream)](https://github.com/timdream) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7e3f86c08787)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[timdream Timothy Guan-tin Chien (timdream)](https://github.com/timdream) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5a3652bcb743)

**Pull request merged**
