### PR TITLE
Bug1145758 - remove old endedTimer workaround

### PR DESCRIPTION
**Pull request by davidflanagan**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e1afa571741ab6af24e52c83f5531c2e76ed718d

**Comment by davidflanagan** [comment]
Closing, editing title, and reopening to make autolander happy

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e1afa571741ab6af24e52c83f5531c2e76ed718d

**Pull request closed without merging**
