### PR TITLE
Bug 1141799 - Bulgarian keyboard layouts update

### PR DESCRIPTION
**Pull request by chilyashev**
Hi,
This is the pull request for bug 1141799 (https://bugzilla.mozilla.org/show_bug.cgi?id=1141799).

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[chilyashev Mihail Chilyashev (chilyashev)](https://github.com/chilyashev) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=757db5b49c79)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=10fd083440070691741fd2ebf060cbb6b591d3b9

**Comment by StoyanDimitrov** [comment]
Is there a problem with the code we need to fix in order this PR to be accepted?

**Pull request closed without merging**
