### PR TITLE
Bug 1068698 - Email list should be listbox with list items.

### PR DESCRIPTION
**Pull request by goetsu**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[goetsu goetsu](https://github.com/goetsu) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4f9314582416)

**Comment by try-server-hook** [comment]
[goetsu goetsu](https://github.com/goetsu) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b198fdf6c4fc)

**Comment by yzen** [comment]
^ retriggering the tests.

**Comment by try-server-hook** [comment]
[yzen Yura Zenevich (yzen)](https://github.com/yzen) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8965261bcf6a)

**Comment by try-server-hook** [comment]
[yzen Yura Zenevich (yzen)](https://github.com/yzen) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ed111311fa62)

**Pull request merged**
