### PR TITLE
Try fixing things.

### PR DESCRIPTION
**Pull request by KevinGrandon**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ecb5e033525cb3379c2695eac89fccc1f0917573

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=33a4d22854f801334d4b819c72b8948614cffa36

**Pull request closed without merging**
