### PR TITLE
Bug 1175260 - Land l20n.js

### PR DESCRIPTION
**Pull request by stasm**
https://bugzilla.mozilla.org/show_bug.cgi?id=1175260

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8bae6245f0b49eba84cc6cadb02ef2d5a61d36b9

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a4dad05362cf78a6fe329f788d14e90feafcfcda

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3479598b5780982e9446fe7418e09c8e060488a7

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dfad91e478ff8b31371eaba05cfb33c97d0f5f6e

**Pull request merged**
