### PR TITLE
Bug 1176015 - Base the minimized statusbar width on the shadow, instead of the chrome r=gmarty

### PR DESCRIPTION
**Pull request by albertopq**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=aa7bd7b07aa6218e3970badf854d84f3d40f5fbb

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=aa7bd7b07aa6218e3970badf854d84f3d40f5fbb

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=aa7bd7b07aa6218e3970badf854d84f3d40f5fbb

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=05d73ab479050aaef367f0fc34ac6e570f4ed46e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=05d73ab479050aaef367f0fc34ac6e570f4ed46e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b4a1a2f7ef351932762543439224e36447af1601

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=61726042ccdafd4b56feb92f4f6d233cf14bd72b

**Pull request merged**
