### PR TITLE
Merge pull request #29835 from mikehenrty/gmarty-Bug-1159885-Status-b…

### PR DESCRIPTION
**Pull request by mikehenrty**
…ar-is-not-visible-on-multiple-attention-windows

Gmarty bug 1159885 status bar is not visible on multiple attention windows
Conflicts:
    apps/system/test/unit/statusbar_test.js

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4be58ec01723975b9b67f574664a0c5571bc0216

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b989d507c1146a7d5f10da5a8c52441ad11f1b73

**Pull request merged**
