### PR TITLE
Bug 1214677 - [Messages] We should not see the highlighting color on phone numbers in message report when clicking on them phone numbers in message report when clicking on them

### PR DESCRIPTION
**Pull request by kumarrishav**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7f6edffe0bf87e4aef1a46a8ea6af8f18a4d052a

**Comment by julienw** [comment]
You can also remove the rule for `.report-view > .contact-list a` in `views/conversation/style/report_view.css`

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=55303d25d6b06ea3649692c7f9708e3cc0952665

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=accd940ee1fe4f62a748f085241aa69e300fbdbc

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5c1541c97e9b7ad2b2b6880974a33f2022e39422

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dba49de21168ee8f8925fe7c80601d5c10e0f7b3

**Pull request merged**
