### PR TITLE
Bug 1113953 - Bug 1097754 Follow up - Centralizing the default Plivo tim...

### PR DESCRIPTION
**Pull request by JohanLorenzo**
...eout value

### CODE REVIEW

**Comment by try-server-hook** [comment]
[JohanLorenzo Johan Lorenzo (JohanLorenzo)](https://github.com/JohanLorenzo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4e14f7a4c90f)

**Comment by geoelectric** [comment]
Mostly LGTM. We've gone from timeout= kwarg to a positional argument. I think probably we want to maintain the kwarg so timeout=PlivoUtil.DEFAULT_TIMEOUT would be better.

That said, we did centralize the constant but should we go one step further and write PlivoUtil wrappers for the Wait on is_call_completed() and is_call_connected()? They're all over the place.

I'm kind of wondering if we shouldn't have:

def wait_for_call_completed(self, call_uuid, timeout=DEFAULT_TIMEOUT)
def wait_for_call_connected(self, call_uuid, timeout=DEFAULT_TIMEOUT)   

as two methods on PlivoUtil. They'd just contain the Wait wrappers we're already doing (but against self instead of self.plivo, of course).

Your call on that one. I do think the kwarging should be fixed prior to merge though.

**Comment by try-server-hook** [comment]
[JohanLorenzo Johan Lorenzo (JohanLorenzo)](https://github.com/JohanLorenzo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f5f7476c7316)

**Comment by try-server-hook** [comment]
[JohanLorenzo Johan Lorenzo (JohanLorenzo)](https://github.com/JohanLorenzo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8a264686035e)

**Comment by geoelectric** [comment]
Looks great, much cleaner. Thanks for the wrappers!

**Comment by try-server-hook** [comment]
[JohanLorenzo Johan Lorenzo (JohanLorenzo)](https://github.com/JohanLorenzo) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ff04ecf4eea1)

**Pull request merged**
