### PR TITLE
Bug 1159818 - Update marionette-client r=bustage

### PR DESCRIPTION
**Pull request by lightsofapollo**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e883cac913d4309c5568384b4767e04d39bd6c8d

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=277ff361005fc37b764e01e2d32fec072a0189af

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=277ff361005fc37b764e01e2d32fec072a0189af

**Pull request closed without merging**
