### PR TITLE
Bug 1189221 - [TV 2.5][Home] Separate upper left corner icons into each individual icons with only 1 layer

### PR DESCRIPTION
**Pull request by Fischer-L**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b766273b0e17498890709261b00cfe4b32c435a2

**Comment by rexboy7** [comment]
You should also remove the logic for keeping `settingsGroup` open in `checkFocusedGroup`.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=da68a77d44d1a8d51a9b69b4ab695b1b1d4002cd

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9a91a825f72c449d78f9d2d702c714727de47eb9

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8ef6905a56d9b71d15a8b1e01f87e2776476e1a9

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=fcc3ddb053624385d9466974b1424cbddb66b07e

**Comment by Fischer-L** [comment]
Already remove the logic for keeping settingsGroup open in checkFocusedGroup

**Pull request merged**
