### PR TITLE
Bug 1169361 -  Switch to require('./l20n') in webapp-optimize

### PR DESCRIPTION
**Pull request by stasm**
https://bugzilla.mozilla.org/show_bug.cgi?id=1169361

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6e602c86eea6753ef4ba62c2914c3cf13df8e927

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=70e620b5764b7dfca2918b296d9f003fa36363d5

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ebc92dfb9c85db237406b80776e62b7ee393bf6c

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ad4c9760acbc71bd98e12278d8f30f0374a4320d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7dc6713b8d7128bb7c244abff1cd7a26c3d6e597

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f7691307d866aac357ef02ac99bd285c3bc34f8d

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9474ea80911a305daea8000128b7dbf07eeebaf3

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=113401ca536176f2c5b4bfbaf5581439ff14548f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5f7985d57da67b7cdfb3a5b6f30026271c5eb7f3

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=885686d4b4cc1c16491929cfa3d14b19be1fa53f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0ca689a8dad6fbec9d70d23c8e0ac9485f9caaa7

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4624fc9c1f11747c8cc0fcdc7c243af9ef608672

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b3672b8d13588de6cf757763d4195b27d0f1ffa4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0fba923e219f70d89ac62393b2d85e52542e50aa

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b2a36363ca74f38e3e1c3f8a37a1021c43eb737e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=39fcb420ad39afb2d047e6c38a69bc23b507c8a2

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1cc59e94ed136d3347eabb5c28982646de29794c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=268e2de0ca99989dc5e178960e951dbb51b87523

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b55011be43395ca9655f255dd4bf1111b619785d

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e198860ccaac66946bcfb6b7e8b0acef76e8767

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a27de5b68b5ef5b3cfd1d739cb53de05f2fd3e44

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=01d4399f8b7a6b7f2d4a10ea417639af6b0d2049

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f09d61c54e015f5e7eea0eac00d01067830a89dd

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=87b4f52e7623c8514fb9277c1e62ea61e7073eeb

**Pull request merged**
