### PR TITLE
Bug 1079763 - Compress logs produced by LogShake

### PR DESCRIPTION
**Pull request by hobinjk**
Updates references of logFilenames to instead use zipFilename. Updates unit
tests of LogShake accordingly.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3e3311bbe3bc0fca709fe48b7d8c6e7f25c507c9

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d0a76ec6be95fb3e9fc47ac20c1f88c427e6b6f3

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9eb644250c6c735bc1bbac8fcac758c9af157101

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=520179c18213fc5393ba96958db24e202caaca9f

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f972b02c2bdc0a613dacc7a2f5369b51647d976e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=97076120858bb9adf02af3ad4508d1f11110b96b

**Pull request merged**
