### PR TITLE
Bug 1124992 - Use the promise resolution to display error message when adding calls to a conference r=thills

### PR DESCRIPTION
**Pull request by gabrielesvelto**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8b57978a434798604c5cba3dff28806937308408

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1d370827a2dbf2a9d122380c3a415a9d8591ae56

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=26206596b996b9c100b63fe5251ef19131f39480

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#rsnN-AV9TkeBdu3uB6sR8Q

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
