### PR TITLE
Bug 1105548 - [Messages] Notifications for messages will still be present when a message is received while in the message thread opened from contacts. Use InterInstanceEventDispatcher to detect if Thread panel is opened somewhere else.

### PR DESCRIPTION
**Pull request by azasypkin**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0c98cee7721e)

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d59a43868daf)

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=fbcf6e9dec47)

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c66783b1a433)

**Comment by try-server-hook** [comment]
[azasypkin Aleh Zasypkin (azasypkin)](https://github.com/azasypkin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0e6e68843885)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a3dda0a8c330bda6cbb191b3d0cd48952b7ca382

**Pull request closed without merging**
