### PR TITLE
Bug 1165160 - [Stingray][system] turn off focus fallback catcher by d…

### PR DESCRIPTION
**Pull request by huchengtw-moz**
…efault

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=63ed5ae634672af2228c5ed78d97019070d17452

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#2-Z9D8zRRvKrxXkK9Fbhig

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7bac57340a54a849bcea27df22cf3eb800336f39

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0d94e4e90cb5b6326eca1239672d9bf839cd3854

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=102c44ffe614afb2f863119608723cd0e9fa3dfe

**Pull request merged**
