### PR TITLE
Bug 1157163 - Fix how camera may be reopened too early when using the preview gallery.

### PR DESCRIPTION
**Pull request by aosmond**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=30ebd56f8dd3fc276420d7d29cd4555e0626744e

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#JKASrL5qQ9SJwb2PmgjhlA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1454923b97223f2456c4e8839c3af718d63f64c8

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f57f7d655bc68c7ad2ba31bf13dd75102154c077

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f57f7d655bc68c7ad2ba31bf13dd75102154c077

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#ry0AY-nhS9CYkfsDTDi6yQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f57f7d655bc68c7ad2ba31bf13dd75102154c077

**Pull request closed without merging**
