### PR TITLE
Bug 1224203 - Update Kinto.js to version 6ea1cf5 (1 December 2015), r=ferjm

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7491530c8b3d31b679d942e3442f36e40b92c82d

**Comment by michielbdejong** [comment]
If the fix gets merged into Kinto.js, we'll get it in the next Kinto.js version update.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=387b7ba45d9cf3b96fc3e859cc26e8f6c2fe58ab

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c6f9c1296911f066a25b7cceab7a945925e3ce91

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2fa6b60d2e42cf7e202497dc72882aca5d4725fa

**Pull request merged**
