### PR TITLE
Bug 1252427 - Remove FTU App 

### PR DESCRIPTION
**Pull request by sfoster**
Remove the FTU app and explicit dependencies on the current FTU implementation. 
System app mostly untouched, allowing for future FTU apps (e.g. Service.isFtuRunning not removed)
NOFTU defaults to true

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=330f80fce80933ccde8ec287d1b431ddf3eef774

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c4267045e2f5da2b6f2863dccb89bd9e5351d186

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=92020290765578aa20cf24774746a62f0095fb1e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c6c383e6c76deae9da099d8ba11a8fa684630fa1

**Comment by ehabab** [comment]
العمرلخظه

**Pull request closed without merging**
