### PR TITLE
Bug 1152727 - Fix jshint error in system app marionette test

### PR DESCRIPTION
**Pull request by shamenchens**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3060464a7d24668d9d419de627eebf9b35ed8776

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=34377e6a9341e1452baf8b53abf65fa344872e91

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=966f103b6930935c3678dfeb062d0e46fb8dd569

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#oszbiZ0oQDOK6B9cbxI4aA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=325fc3e1dc2c080d18fd2d551c65f9d53c83ecbe

**Pull request merged**
