### PR TITLE
Bug 1203885 - Wrong number of merged contacts on importing

### PR DESCRIPTION
**Pull request by fcampo**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=082f5f31b57c9c5e51740fb9acfcc0d9f5cd803e

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=555ef5075f18e01240560593136a5b57f318b3c5

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=555ef5075f18e01240560593136a5b57f318b3c5

**Comment by arcturus** [comment]
Closing and reopening to trigger unit tests

**Pull request merged**
