### PR TITLE
Bug 1135660 - Add transitions to gaia-confirm. r=kgrandon

### PR DESCRIPTION
**Pull request by Cwiiis**
Add transitions to gaia-confirm and make sure they don't get overridden
by ConfirmDialogHelper.

### CODE REVIEW

**Comment by try-server-hook** [comment]
[Cwiiis Chris Lord (Cwiiis)](https://github.com/Cwiiis) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8a4cb2341167)

**Comment by try-server-hook** [comment]
[Cwiiis Chris Lord (Cwiiis)](https://github.com/Cwiiis) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=09a89b6d5343)

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#041Xp2msRiuIt9iT6qC1lg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by try-server-hook** [comment]
[Cwiiis Chris Lord (Cwiiis)](https://github.com/Cwiiis) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=52b06bdc20f9)

**Pull request merged**
