### PR TITLE
Bug 1137613 - [System] The animation that shows a notification feels slu...

### PR DESCRIPTION
**Pull request by julienw**
...ggish r=mhenretty

### CODE REVIEW

**Comment by try-server-hook** [comment]
[julienw Julien Wajsberg (julienw)](https://github.com/julienw) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=83b699441c2c)

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=aaf35777f9570002313baf1bf8aa837c50a3a297

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=3e88ca52439af1f3f233d4feb4a41a69a0ee79a2

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=72b80dd73e6180b99848a8ab2d3981d4af8b8d2d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=72b80dd73e6180b99848a8ab2d3981d4af8b8d2d

**Pull request merged**
