### PR TITLE
Bug 1146877 - Intermittent test_ftu_skip_tour_desktopb2g.py

### PR DESCRIPTION
**Pull request by mwargers**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d66aff97c8eb74f1e4349889a5e71cba50ffc146

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d66aff97c8eb74f1e4349889a5e71cba50ffc146

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#SQpa-oDGQYCfeXHMONJ4rw

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d66aff97c8eb74f1e4349889a5e71cba50ffc146

**Pull request merged**
