### PR TITLE
Bug 1222995 - Notifications tray can get stuck partway open when powe…

### PR DESCRIPTION
**Pull request by mcav**
…ring off the screen, obscuring the lock screen.

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=56e43574694f67c978043977934405a4db7cd608

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cb0bc7a6fee2975f3b8bfaddf62ee5d48a707b20

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=aaa6d9faee502c4bca02db1684b77cb275c630d0

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ff6aa773b0dac5e228b1028267964c8f41b72a26

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c21377d12c48ce804946aaf6541eb217a33ec7b1

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c21377d12c48ce804946aaf6541eb217a33ec7b1

**Comment by ehabab** [comment]
ehabab

**Pull request closed without merging**
