### PR TITLE
Bug 1162383 - Wait for content process to paint before hiding the keyboard

### PR DESCRIPTION
**Pull request by timdream**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c10625493b9aa0b274bde8848cf48d39c2a69f0d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=900059bfbcef4001c7f2dd8a2c8502a002d1d20f

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f7c4b73c40c9f624a9d011ec2c67cb62db51b267

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=99456d6f321ebdeccc0cdecc4a96a3c42c2031e3

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d08c0d5368ae6e8ab9c3be8ca0ade61185aa3f42

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#RU1hsYdsRAi-xZh5e-2pEA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
