### PR TITLE
Bug 1166006 - [music] Use smooth scrolling for the search box

### PR DESCRIPTION
**Pull request by jimporter**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0dcafd1c6162ca67f41624c2226ad2b469e5604b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9037df82ccd8cf5b519ca9e97674e378b0f32b52

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d5e281bb7b7139b472b563b32c165645d3fe14d2

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e3f1901b700286ce8087697c3374902f6717c13

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=290d5afa3e17c913ef1bfb0cc763b35e76e58052

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=889ddb49c11e482a28cb91f0ea19806f50acfe03

**Comment by jimporter** [comment]
Closing this, since the music app is being replaced.

**Pull request closed without merging**
