### PR TITLE
Bug 1156141 - Make switch from boot animation to first system app screen...

### PR DESCRIPTION
**Pull request by msliu**
... seamlessly. r=vivien

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d4d570587d42f56f571d98862d7cf8d3526d36d5

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0412b5ff111f7d1e006c41a1a34822df44128dcf

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#zBZc7dMjQrCAwYZgdu0nOA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#RyGmlW-1S8m4JG44r-f0NA

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8de59b65e40e3ed64e12eb4a628147084fb7c246

**Pull request merged**
