### PR TITLE
Bug 1126591 - Update Marketplace app package r=julienw

### PR DESCRIPTION
**Pull request by diox**
https://bugzilla.mozilla.org/show_bug.cgi?id=1126591

### CODE REVIEW

**Comment by try-server-hook** [comment]
[diox Mathieu Pillard (diox)](https://github.com/diox) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=62dac9e56d39)

**Comment by try-server-hook** [comment]
[diox Mathieu Pillard (diox)](https://github.com/diox) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=cefb8da620b4)

**Comment by try-server-hook** [comment]
[diox Mathieu Pillard (diox)](https://github.com/diox) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=283aa2b05cc7)

**Comment by clouserw** [comment]
Once those tests pass I'll land

**Comment by clouserw** [comment]
all tests pass, landing. Thanks.

**Pull request merged**
