### PR TITLE
Bug 1283572 - Convert tasks to use v2 treeherder routes

### PR DESCRIPTION
**Pull request by gregarndt**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=313a4b73355927a8a26460d61a43811b9854d9c8

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5dc405c89585d61bd6df0b0b6bc03037c836c7f2

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=cf77fcc1f814705159aafc5e4fac607f9fcc6a73

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4467ca9994e524894d6584318ec3f7e427945ed4

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0b8444ccdccef99a09834c62132a30b24235b276

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=752aae361ab088856abefe4654f38cdd00d36e05

**Comment by gregarndt** [comment]
Thank you!

**Pull request merged**
