### PR TITLE
Bug 1113061 - [Email]You can't select a picture attachment for email after unplug usb.

### PR DESCRIPTION
**Pull request by begeeben**
...ist will be refreshed when the photodb is ready.

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[begeeben Yi-Fan Liao (begeeben)](https://github.com/begeeben) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=fccb7eb1ac0f)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[begeeben Yi-Fan Liao (begeeben)](https://github.com/begeeben) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=051c10b520fc)

**Pull request closed without merging**
