### PR TITLE
Bug 1186388 - Make a PEP8 linter run on every commit on stage

### PR DESCRIPTION
**Pull request by JohanLorenzo**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c2aa8924a4870c557eb9c9697d2e5300fcb39609

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=fbe69d3dbe35bc75fa891a83c1cc7db06b330152

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a4a9549d16ac9fcfcce99459c330490f9e933e4c

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dc88e05a5938a1239be2912e3effc956784c6cdf

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0b25edfac3cdff11aad29ce542fdaf9cdc14da32

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e629c333941ea21dd4b2525024343fad18259a93

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=25fa4fb467b5b595604513ea3cd3d71a498f60ef

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1267c408ac6e6a2c8edb058beb30b3ee8e39e003

**Comment by JohanLorenzo** [comment]
Mass closing PRs. Gaia is not a supported project anymore.

**Pull request closed without merging**
