### PR TITLE
Bug 1158447 - fix SMTP dot stuffing. v2.2-specific, r=mcav

### PR DESCRIPTION
**Pull request by asutherland**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9e1f6b62564069a90ada0d789c921f1dbc8530aa

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b8e556e01d634347d5f2880f327905b1fbea2f72

**Pull request merged**
