### PR TITLE
Bug 1211972 - Use --trusted-host with PIP v7 and above r=aus

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c8c048886d437d7ef25282e5859e34bb8fe2a6a7

**Comment by nullaus** [comment]
lgtm, merge when tests pass.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0444490a91276b4e79e17d30273914d99855115a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e25cdea52c08597388fdafe32c8e21112ca3327

**Pull request merged**
