### PR TITLE
Bug 1198172 - Use somewhat standard delay of 30s to bootstrap things.…

### PR DESCRIPTION
**Pull request by nullaus**
… r=me

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=88da49312aa9811d45051f5c27cfabba3be83db3

**Comment by julienw** [comment]
does not look better :(

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e5979c996075e2691317a9420025e3e74495f43d

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=34cce646c1ed270efc599b1a8bfd66776e573788

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2e848637cabe2ae5bbf278fed7d1c45d002ea736

**Pull request closed without merging**
