### PR TITLE
Use L20n.js in FM Radio

### PR DESCRIPTION
**Pull request by stasm**
No bug yet;  testing Raptor for now.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=619018b763364c52effa079fc0ee4d886fe0f5c3

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d2ebcbd5a53b010dc499c5f4635836b0d339a168

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=120c7d11382fd3bbe40b5033cc16b00df597ee95

**Pull request closed without merging**
