### PR TITLE
Bug 1109820 - Restart calendar when timezone changes r=millermedeiros

### PR DESCRIPTION
**Pull request by lambdabaa**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[gaye Gareth Aye (gaye)](https://github.com/gaye) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e4e173dd9d6a)

**Comment by millermedeiros** [comment]
can you also fix the code:

```js
window.addEventListener('moztimechange', () => {
  debug('Noticed timezone change!');
  nextTick(() => this.forceRestart(), this._mozTimeRefreshTimeout);
});
```

`nextTick` makes no sense here.. it was supposed to be a `setTimeout` and the `this.restartPending` was used to safeguard against multiple changes in a row..

**Comment by millermedeiros** [comment]
or if you think the `nextTick` is enough we should remove the `_mozTimeRefreshTimeout` since it is not being used anymore..

**Comment by gaye** [comment]
Haha wow

**Comment by gaye** [comment]
Yeah let's just get rid of the `_mozTimeRefreshTimeout` bit

**Comment by gaye** [comment]
Multiple timezone changes wouldn't hurt us if we use `nextTick` afaict since `window.location.href` would only ever be set once per tick of the event loop (even if the user is changing timezones multiple times in quick succession)

**Comment by try-server-hook** [comment]
[gaye Gareth Aye (gaye)](https://github.com/gaye) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c277f6f02fd9)

**Comment by try-server-hook** [comment]
[gaye Gareth Aye (gaye)](https://github.com/gaye) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=72bc5e9f8909)

**Pull request merged**
