### PR TITLE
Bug 1105986 - [stingray][home] Implement 'delete card' button +autoland

### PR DESCRIPTION
**Pull request by rexboy7**

### CODE REVIEW

**Comment by dwi2** [comment]
It seems that there are some conflict between this patch and master. Would you rebase to latest master? because I'd like to try it out on my site. Thanks

**Comment by dwi2** [comment]
I am ok with the structure overall. But we forgot to do one thing here: Decks cannot be deleted. I think we should do that here.

**Comment by try-server-hook** [comment]
[rexboy7 Rex KM Lee (rexboy7)](https://github.com/rexboy7) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8e74db2078cb)

**Comment by try-server-hook** [comment]
[rexboy7 Rex KM Lee (rexboy7)](https://github.com/rexboy7) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=8ba6311557aa)

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[rexboy7 Rex KM Lee (rexboy7)](https://github.com/rexboy7) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=04c187ac91b0)

**Comment by autolander** [comment]
The pull request could not be integrated in as it contained a commit which was missing a bug number. Please ensure all commits contain bug numbers, and are in the format of: Bug [number] - [description]

**Comment by try-server-hook** [comment]
[rexboy7 Rex KM Lee (rexboy7)](https://github.com/rexboy7) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=6c90be28abf5)

**Comment by try-server-hook** [comment]
[rexboy7 Rex KM Lee (rexboy7)](https://github.com/rexboy7) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f030917cef8f)

**Comment by try-server-hook** [comment]
[rexboy7 Rex KM Lee (rexboy7)](https://github.com/rexboy7) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e1c6d7539ca7)

**Pull request merged**
