### PR TITLE
Bug 1205578 - [lockscreen] lockscreen still milky colored even if all notifications are cleared r=timdream

### PR DESCRIPTION
**Pull request by prateekjadhwani**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dca0d087cd0e919fb3f1e9778384b2b7879d2308

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=50ddc3cc1b4fffb1ae2b1fecbb07c7387527660a

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2911f909c2b3ff671ce8a03db3941a1242e30fea

**Comment by prateekjadhwani** [comment]
Closing this PR and reopening it in https://github.com/mozilla-b2g/gaia/pull/32775

**Pull request closed without merging**
