### PR TITLE
Bug 1082618 - [Messages] add a README file r=schung

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
So, comments! This is looking pretty good overall. A few specifics:

0. Is the app actually called "Messages"? I thought it was called "SMS".

1. The "How to run the application in Firefox" section - this works now? I thought this didn't work at all? I am also kinda confused as to why work would be done on this when Mulet is supposed to be the answer going forward.

2. The "Filing a good bug" section. We already have this page about bug submission for Firefox OS: https://developer.mozilla.org/en-US/Firefox_OS/Developing_Firefox_OS/Filing_bugs_against_Firefox_OS. You could add the info here, first checking that none of the info is already covered on this page or any of the ones it links.

The more general guide is here: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

3. "Provide a screenshot..." - I have a guide to all the ways you can take screenshots at https://developer.mozilla.org/en-US/Firefox_OS/Debugging/taking_screenshots. Adding some details here would be good, if you have details that I've not included.

4. "Fixing the bug and proposing a patch" in this section, you say "Be careful as MDN explains how to run the full Gaia in Firefox but we rather use the steps described above for the Messages app development". Do you just mean the stuff said in the "How to run the application in Firefox" section? It seems to me like you ought to write something SMS app specific about Mulet too, before deferring to MDN for a more detailed, specific guide.

5. A general comment: I would have expected a bit more information on how the messaging app actually works - how to find your way around the architecture, etc. I did try to write such guides at https://developer.mozilla.org/en-US/Firefox_OS/Platform/Gaia/Gaia_apps, but I gave up because the apps tend to change very rapidly; it is probably way out of date. Ideally, I think these kind of guides would work better in Github READMEs, maintained by the app developers.

**Comment by try-server-hook** [comment]
[julienw Julien Wajsberg (julienw)](https://github.com/julienw) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5700aa5eb351)

**Comment by try-server-hook** [comment]
[julienw Julien Wajsberg (julienw)](https://github.com/julienw) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ca2a0b7025ec)

**Comment by julienw** [comment]
Hey Chris, thanks a lot for your comments and corrections :)

> Is the app actually called "Messages"? I thought it was called "SMS".

It's really called "Messages" on the phone :) Because after all we can send MMS too.

> The "How to run the application in Firefox" section - this works now? I thought this didn't work at all? I am also kinda confused as to why work would be done on this when Mulet is supposed to be the answer going forward.

This is a trick to run the SMS app only, and not all Gaia. We're simulating some APIs so that we have dummy data.
However we can't run the whole Gaia system in Firefox. For example, we miss cross-application relationships like activities when we run the SMS app only. and that's what Mulet is about.

> The "Filing a good bug" section. We already have this page about bug submission for Firefox OS: https://developer.mozilla.org/en-US/Firefox_OS/Developing_Firefox_OS/Filing_bugs_against_Firefox_OS. You could add the info here, first checking that none of the info is already covered on this page or any of the ones it links.

> The more general guide is here: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

Thanks, I'll look at that.


> "Provide a screenshot..." - I have a guide to all the ways you can take screenshots at https://developer.mozilla.org/en-US/Firefox_OS/Debugging/taking_screenshots. Adding some details here would be good, if you have details that I've not included.

Cool, I'll add the link !

>  "Fixing the bug and proposing a patch" in this section, you say "Be careful as MDN explains how to run the full Gaia in Firefox but we rather use the steps described above for the Messages app development". Do you just mean the stuff said in the "How to run the application in Firefox" section? 

Yep, that's it.

> It seems to me like you ought to write something SMS app specific about Mulet too, before deferring to MDN for a more detailed, specific guide.

Yeah I know I need to write something about Mulet but I don't know this very much yet so I thought we could do it later on.

> A general comment: I would have expected a bit more information on how the messaging app actually works - how to find your way around the architecture, etc. I did try to write such guides at https://developer.mozilla.org/en-US/Firefox_OS/Platform/Gaia/Gaia_apps, but I gave up because the apps tend to change very rapidly; it is probably way out of date. Ideally, I think these kind of guides would work better in Github READMEs, maintained by the app developers.

Perfectly agree except I'd see this in https://wiki.mozilla.org/Gaia/SMS instead. But we can link from the README. To me the README is more a quick start procedure with links to more complete guides.

Thanks again for your time!

**Comment by chrisdavidmills** [comment]
no problem - I'm happy to help.

**Comment by julienw** [comment]
landed in 17cd52956a545a8ef604a76f816b4ddb3e336802

**Comment by try-server-hook** [comment]
[julienw Julien Wajsberg (julienw)](https://github.com/julienw) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2b061e8e13a7)

**Pull request closed without merging**
