### PR TITLE
Bug 1129411 - Failure in test_calendar_new_event_appears_on_all_calendar...

### PR DESCRIPTION
**Pull request by viorelaioia-zz**
..._views.py, Add event button is not tapped

### CODE REVIEW

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2d347af7861b)

**Comment by viorelaioia** [comment]
http://jenkins1.qa.scl3.mozilla.com/view/UI/job/flame-kk.ui.adhoc/669/console

**Comment by viorelaioia** [comment]
http://jenkins1.qa.scl3.mozilla.com/view/UI/job/flame-kk.ui.adhoc/685/console

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4818f140e2cd)

**Comment by viorelaioia** [comment]
http://jenkins1.qa.scl3.mozilla.com/view/UI/job/flame-kk.ui.adhoc/692/console

**Comment by try-server-hook** [comment]
[viorelaioia viorelaioia](https://github.com/viorelaioia) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=af0fee41991a)

**Pull request closed without merging**
