### PR TITLE
Bug 1270400 - [TV][Home] Press left arrow key on the first card in folder shouldn't navigate to filter

### PR DESCRIPTION
**Pull request by luke-chang**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=bcec2b5a3bfa3e91ead3babcaec69ed7b748980f

**Comment by rexboy7** [comment]
The comment of this bug looks like you want to add a feature to navigate to feature. Please make some change like `shouldn't navigate to filter` or `should have no any effect`

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f59752da6d012c6229a34229c17fa6fbd08d2014

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f59752da6d012c6229a34229c17fa6fbd08d2014

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=e536d019a887d7443a9501512ac4815795c76014

**Pull request merged**
