### PR TITLE
Bug 1156188 - [Stingray][TvDeck] Use asyncStorage instead of localStorag...

### PR DESCRIPTION
**Pull request by sean2449**
...e for storing last TV settings

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=432d101709a4d41039650aacdf2122942948d3d2

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#tU8tHn2TTaO34G213E3Xqw

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#s2yF7KY0SJCEBseSDYAHjg

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1f9a4a3f12526c1d7fd2b9b18daa9c5ad75a9107

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#-6cduB0jS06ojjkhWDU6JQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
