### PR TITLE
Bug 1196441 - overlay tests

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=98ce38b91c9f70aaa71e8d50d035662b0434e680

**Comment by hfiguiere** [comment]
Will have failures related to the activity tests.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=2dcdfed6b08ec1eabfd8b2e60c8f6e165acf0837

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=5f144555212b8347dcd1470f1749cbb217f8bb5a

**Pull request merged**
