### PR TITLE
Revert "Revert "Bug 1095712 - Reenable disabled calendar marionette t…

### PR DESCRIPTION
**Pull request by lambdabaa**
…ests r=gaye""

This reverts commit 1870f546a92b99c6e1aa2e98e56d9b28eeee61d3.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d4945ff770ff4af7852d81772c7594be4c3f5d6d

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#o3uI7vvkRLmTqARjVwpr6Q

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f8abd450d12eddc4b6098b4e936f219109de40ad

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#NJAvO9x5SqKt67BOr0lgow

The pull request failed to pass integration tests. It could not be landed, please try again.

**Pull request merged**
