### PR TITLE
Bug 1164015 - Update test_setup_and_send_receive_imap_email.py imagecompare test

### PR DESCRIPTION
**Pull request by nojunpark**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f666fc4554685ac3e34e98d1993ab61715f0fc12

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=270bd5f25e9f24b8ab672c8114ab8bf1fd9123c7

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=592fd2ccaef996f3cae6c95b33b767f2af6f4462

**Comment by autolander** [comment]
The pull request could not be integrated in as it contained a commit which was missing a bug number. Please ensure all commits contain bug numbers, and are in the format of: Bug [number] - [description]

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a3f8cc488227bb77c84de03b28b9964d2ac7015d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=204e7696d6812772e7a2e6b771e712e6fc0ddefa

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=4b02a8c6053d14905bf57faed87d77a8131d09db

**Pull request merged**
