### PR TITLE
Bug 1137970 - [b2g] Generate Ukrainian (uk) wordlist/dictionary

### PR DESCRIPTION
**Pull request by artpoli**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=dd7d25d44aa5946d6f54fea1ab42f507cbb41885

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7b078e8d80837970b4d9158508eb7939455b0efc

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d78cd05d139ca03e71e6a5c2bfcb2ec788adb798

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ea301aa16b3e1eebe1555e88ada9c748bcbc67a2

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=86d496a40a79d1b22b3803b2a4cfb76f615d1a50

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=370511577d3fccf66310c84d049a8c7b12ffb3bb

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=84095c9efe25928f1d6258376abde7963247f9c4

**Comment by timdream** [comment]
Merged in #34074

**Pull request closed without merging**
