### PR TITLE
Bug 1260089 - Ignore a deleting operation for a non-existing bookmark record

### PR DESCRIPTION
**Pull request by weilonge**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=75edefdcc7c9a7734f2900908574cfad119755dd

**Comment by michielbdejong** [comment]
As discussed on irc, please make this change in both the bookmarks and the history adapter (as they are copy-pasted versions of the same code which for the moment we're not refactoring).

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=900dc17fff282494b85caf6f8d3f5e44f1d9b2b6

**Comment by michielbdejong** [comment]
r+ (apart from TreeHerder which looks a mess, but I guess that's just business as usual nowadays?)

**Pull request merged**
