### PR TITLE
Bug 942365 - fix done button problem in different scenario, r=Arthur

### PR DESCRIPTION
**Pull request by EragonJ**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=eff0f319abb85644d0922a2c7ecbd830ec3fe0f8

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b7035618df07ddc9acd40958ab51e5f48b1336a2

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=82101d4519af628d058c74772433ff2860ae0ebb

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=278a0f038fe128cca02e497d2396680e48d03aa4

**Comment by EragonJ** [comment]
Based on Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b7035618df07ddc9acd40958ab51e5f48b1336a2

Our patch is good to be merged.

**Pull request merged**
