### PR TITLE
Bug1229096 - Check major version of npm for compatibility. r=yzen

### PR DESCRIPTION
**Pull request by nullaus**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c04518ceeb82513f395527a0dd867ded2842cc86

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0c25220033e8a44beb0f3612355d0cbbad661217

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0c25220033e8a44beb0f3612355d0cbbad661217

**Comment by michielbdejong** [comment]
It seems this commit is fine by TreeHerder, but it is causing the following error when I run `make` locally on Mac OS:

> Michiels-Laptop:gaia Michiel$ make clean
/bin/bash: --: invalid option
Usage:	/bin/bash [GNU long option] [option] ...
	/bin/bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
[...]

Anyone else found this problem? Should I update my bash version?

**Comment by nullaus** [comment]
Which version of OS X are you using?

word,
--aus

**Pull request merged**
