### PR TITLE
Bug 1200776 - [Music][NGA] Overlays never appear on b2g-desktop

### PR DESCRIPTION
**Pull request by justindarc**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=c811fd2b0617c2c80d293ac592f5675e32befcd2

**Comment by hfiguiere** [comment]
Before merging, can you disable the two test for the overlays in ````music_test.js```` ? (use ````test.skip````) - I will re-enable / fix them with my next patch.

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=0968dbd20f18b5f28964618402b6ce3bcd6911a4

**Comment by hfiguiere** [comment]
Merged with PR #31589

**Pull request merged**
