### PR TITLE
Bug 1136754 - Update phone number and IMEI test variables to support remote device lab

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c860d1a42cba)

**Comment by geoelectric** [comment]
LGTM

**Comment by try-server-hook** [comment]
[davehunt Dave Hunt (davehunt)](https://github.com/davehunt) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=aaffefefaa12)

**Comment by geoelectric** [comment]
Looks great!

**Comment by davehunt** [comment]
Merged in https://github.com/mozilla-b2g/gaia/commit/1a99204f23e9b84290f2301be550e848794130a3

**Pull request closed without merging**
