### PR TITLE
Bug 1153993 - use the MediaDB enumerable event to improve startup time

### PR DESCRIPTION
**Pull request by davidflanagan**
initialize MusicComms on enumerable instead of on ready

(cherry picked from commit 321ce153cbb977faca4e77fef24bce4ad507ac75)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f491c686156b341fa980f31b82f9d5a5382dd081

**Comment by davidflanagan** [comment]
closing, editing title, and reopening to make autolander happy

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f491c686156b341fa980f31b82f9d5a5382dd081

**Comment by davidflanagan** [comment]
It loses my title edit every time I try that!

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f491c686156b341fa980f31b82f9d5a5382dd081

**Comment by autolander** [comment]
The pull request could not be integrated in as it contained a commit which was missing a bug number. Please ensure all commits contain bug numbers, and are in the format of: Bug [number] - [description]

**Comment by davidflanagan** [comment]
Landing it by hand, then.

**Pull request merged**
