### PR TITLE
Bug 1062558 - Find My Device should ignore system events when disabled

### PR DESCRIPTION
**Pull request by shamenchens**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[shamenchens Sherman Chen (shamenchens)](https://github.com/shamenchens) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=ebfa0462fe24)

**Comment by try-server-hook** [comment]
[shamenchens Sherman Chen (shamenchens)](https://github.com/shamenchens) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=a13b3996bcf6)

**Comment by try-server-hook** [comment]
[shamenchens Sherman Chen (shamenchens)](https://github.com/shamenchens) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=40027da51236)

**Comment by shamenchens** [comment]
I found if we use `SettingsListener` instead, it will trigger when system startup and still send IAC message to notify FMD and launches it. That's not solving the original problem so I tend to not change it.

**Comment by try-server-hook** [comment]
[shamenchens Sherman Chen (shamenchens)](https://github.com/shamenchens) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=eb136bed3e9f)

**Comment by try-server-hook** [comment]
[shamenchens Sherman Chen (shamenchens)](https://github.com/shamenchens) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2a662951c92d)

**Pull request merged**
