### PR TITLE
Bug 1164346 - Add a locale id check hook

### PR DESCRIPTION
**Pull request by EragonJ**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=8e1474841bfd7f4141f959870809607b29eef7e2

**Comment by cctuan** [comment]
Awesome!
However, if I change two properties, it will only print out one change, is that expected ? or probably the / /_ has affected the grep result?

**Comment by EragonJ** [comment]
Good points, let me check what's wrong in my patch.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1e9d88a1daaa84d8476c984ac0898d517178474d

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=ff9faf52827ce431d3e88a814ad626671da53ada

**Pull request merged**
