### PR TITLE
Bug 1218271 - move panel specific styles into app.css

### PR DESCRIPTION
**Pull request by gasolin**

### CODE REVIEW

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=515ad15674b54935a33ae45141b8cf85a3d9e076

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9d9d59b6ac3e54fabb4cafabfbb2d889eac0fb61

**Comment by yzen** [comment]
Overall looks good, 2 things I noticed:

* Developer HUD has Developer Tools sub heading. If you see closely, it looks like it has a top border that is cut off on the left and right side (about 1 pixel).
* Developer HUD color squares have a start padding on a smaller side. I see that it is 1.5rem on padding as it should be, but the square itself seems to go beyond that by a couple of pixels. <- just a nit.

**Comment by gasolin** [comment]
@yzen do you think the above 2 things are introduced by this PR? Or we could fix them in another bug?

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=066a6f40e3f89826b867275c962ab32c5e8f8dbe

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=9d341b251b3dee91185c040aa592e4e474790339

**Comment by autolander** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=f04547ca7be690ab5e3d8365eb860c441448ca6c

**Pull request merged**
