### PR TITLE
Bug 1149886 - using <bdi> to replace <span> at Music app results in unable to locate <span.list-song-index> error

### PR DESCRIPTION
**Pull request by HermesCheng**
a simple fix

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7383df4b527d718ca7fcb1970ef4df143b9d4c32

**Pull request closed without merging**
