### PR TITLE
Bug 1132666 - [RTL][Music] Translated text on music tiles is not right a...

### PR DESCRIPTION
**Pull request by jimporter**
...ligned in Arabic

### CODE REVIEW

**Comment by try-server-hook** [comment]
[jimporter Jim Porter (jimporter)](https://github.com/jimporter) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=6965520a8738)

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#_1jUKHY0RaWtfdWXbIMmOQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6af9622c016cfe417d050469db2050bc822ac41e

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=d5340bf56e361f85f66ef8d941b9572e5191c10c

**Pull request merged**
