### PR TITLE
Bug 1115027 - Making sure the identification-overlay appears instantly and only fades-out r=cwiis +autoland

### PR DESCRIPTION
**Pull request by etiennesegonzac**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[etiennesegonzac Etienne Segonzac (etiennesegonzac)](https://github.com/etiennesegonzac) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c71e57872508)

**Comment by Cwiiis** [comment]
nit, 'cwiiis' and not 'cwiis' :)

**Comment by try-server-hook** [comment]
[etiennesegonzac Etienne Segonzac (etiennesegonzac)](https://github.com/etiennesegonzac) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=3a20a8cbf2ae)

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete.

**Comment by try-server-hook** [comment]
[etiennesegonzac Etienne Segonzac (etiennesegonzac)](https://github.com/etiennesegonzac) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=6ffdeec615f2)

**Pull request merged**
