### PR TITLE
Bug 1169821 - [Settings] USB mass Storage is inconsistently capitalized, r=ej

### PR DESCRIPTION
**Pull request by gasolin**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=530eaf0cfaf41fdb4f8ac3de559b61f7663f5a6b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7573a68a67906963a825011df6a21df4926534ea

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1f826e1566c8cb9aed883999f39565b69ae01ea8

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=6241d573a10e1c24e0a14ad0e284c16aa6375bb0

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#x51_aKjoT861ioOrZhSeYQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=acdc518a5a96505f98e2bc30337ba0012a8aef3c

**Pull request merged**
