### PR TITLE
Bug 1152591 - [Shared] Add variables.css to contain gaia-wide CSS definitions

### PR DESCRIPTION
**Pull request by KevinGrandon**
https://bugzilla.mozilla.org/show_bug.cgi?id=1152591

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b28851397a688624ebb532e95bb711c04abe71bc

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=7037a15a113357b32d273a392acf68006d9839da

**Comment by autolander** [comment]
http://docs.taskcluster.net/tools/task-graph-inspector/#NSPPUqy0T-m3mZo2HIpyqQ

The pull request failed to pass integration tests. It could not be landed, please try again.

**Comment by KevinGrandon** [comment]
This is a fairly common intermittent, so manually landing for now.

**Pull request merged**
