### PR TITLE
Bug 1136275 - Downloading via the browser context menu should use docume...

### PR DESCRIPTION
**Pull request by nullaus**
...ntURI from event data as referrer for 'download' method call. r=kgrandon

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4d01ba7803fe)

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0e2c48e9b849)

**Comment by try-server-hook** [comment]
[nullaus Ghislain 'Aus' Lacroix (nullaus)](https://github.com/nullaus) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=c517065b7aee)

**Pull request merged**
