### PR TITLE
Bug 1158992 - Add new smart collection icon images

### PR DESCRIPTION
**Pull request by jedireza**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b9de6df20eca0161c695730458c36a59a0a31422

**Comment by Cwiiis** [comment]
Just on question before r+, why is the 84x84 icon listed as an 83x83 icon?

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=1771def1362d869f925edde0d87ce7c56f5db52f

**Comment by jedireza** [comment]
I've fixed the 83 -> 84 typo.

**Pull request merged**
