### PR TITLE
Bug 1143226 - (fastandfurious) animations throughout Gaia combine for a generally sluggish user experience (r=TBD)

### PR DESCRIPTION
**Pull request by autonome**

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by try-server-hook** [comment]
[autonome Dietrich Ayala (autonome)](https://github.com/autonome) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=92f9013b6de8)

**Comment by KevinGrandon** [comment]
@autonome - see also: https://bugzilla.mozilla.org/show_bug.cgi?id=1121667

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Pull request closed without merging**
