### PR TITLE
Bug 1116437 - [Bluetooth] promisify Bluetooth getadapter +autoland

### PR DESCRIPTION
**Pull request by gasolin**

### CODE REVIEW

**Comment by try-server-hook** [comment]
[gasolin gasolin (gasolin)](https://github.com/gasolin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f2fa9370f79d)

**Comment by try-server-hook** [comment]
[gasolin gasolin (gasolin)](https://github.com/gasolin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f5bc35c9cdf1)

**Comment by try-server-hook** [comment]
[gasolin gasolin (gasolin)](https://github.com/gasolin) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5d204d40f34d)

**Comment by gasolin** [comment]
replaced by https://github.com/mozilla-b2g/gaia/pull/28826

**Pull request closed without merging**
