### PR TITLE
Bug 1164421 - autocorrect im to I'm not in

### PR DESCRIPTION
**Pull request by davidflanagan**
address review comments

(cherry picked from commit 79e987f19487990de3a53401be85866e464e6f49)

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b4d140f7ed37d2804fd4fea4b78d8e2a9d34947b

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=b4d140f7ed37d2804fd4fea4b78d8e2a9d34947b

**Comment by davidflanagan** [comment]
fixed a lint error and repushed.
We must have switched from gjslint to jshint for latin.js between 2.2 and 3.0 because this was not an issue on the master branch.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=gaia&revision=a4e509f0e9a51d9a916b3e7a98e7de82a8817257

**Comment by davidflanagan** [comment]
The lint error was fixed but the lint tests failed again on the line that had been fixed, so I don't know what was going on there. Force pushed to run the tests again.

**Pull request merged**
